_AWS_APIGATEWAY_METHODRESPONSE_MK_VERSION= $(_AWS_APIGATEWAY_MK_VERSION)

# AGY_METHODRESPONSE_CONTENT_HANDLING?=
# AGY_METHODRESPONSE_HTTP_METHOD?=
# AGY_METHODRESPONSE_NAME?=
# AGY_METHODRESPONSE_PATCH_OPERATIONRESPONSES?=
# AGY_METHODRESPONSE_RESOURCE_ID?=
# AGY_METHODRESPONSE_RESOURCE_NAME?=
# AGY_METHODRESPONSE_RESPONSE_PARAMETERS?=
# AGY_METHODRESPONSE_RESPONSE_TEMPLATES?=
# AGY_METHODRESPONSE_RESTAPI_ID?=
# AGY_METHODRESPONSE_RESTAPI_NAME?=
# AGY_METHODRESPONSE_SELECTION_PATTERN?=
# AGY_METHODRESPONSE_STATUSCODE?=
# AGY_METHODRESPONSES_SET_NAME?= my-method-responses-set

# Derived parameters
AGY_METHODRESPONSE_NAME?= $(AGY_METHODRESPONSE_RESTAPI_NAME):$(AGY_METHODRESPONSE_RESOURCE_NAME):$(AGY_METHODRESPONSE_HTTP_METHOD)
AGY_METHODRESPONSE_RESOURCE_ID?= $(AGY_RESOURCE_ID)
AGY_METHODRESPONSE_RESOURCE_NAME?= $(AGY_RESOURCE_NAME)
AGY_METHODRESPONSE_RESTAPI_ID?= $(AGY_RESTAPI_ID)
AGY_METHODRESPONSE_RESTAPI_NAME?= $(AGY_RESTAPI_NAME)

# Option parameters
__AGY_CONTENT_HANDLING__METHODRESPONSE= $(if $(AGY_METHODRESPONSE_CONTENT_HANDLING), --content-handling $(AGY_METHODRESPONSE_CONTENT_HANDLING))
__AGY_HTTP_METHOD__METHODRESPONSE= $(if $(AGY_METHODRESPONSE_HTTP_METHOD), --http-method $(AGY_METHODRESPONSE_HTTP_METHOD))
__AGY_PATCH_OPERATIONRESPONSES__METHODRESPONSE= $(if $(AGY_METHODRESPONSE_PATCH_OPERATIONRESPONSES), --patch-operations $(AGY_METHODRESPONSE_PATCH_OPERATIONRESPONSES))
__AGY_RESOURCE_ID__METHODRESPONSE= $(if $(AGY_METHODRESPONSE_RESOURCE_ID), --resource-id $(AGY_METHODRESPONSE_RESOURCE_ID))
__AGY_RESPONSE_PARAMETERS= $(if $(AGY_METHODRESPONSE_RESPONSE_PARAMETERS), --response-parameters $(AGY_METHODRESPONSE_RESPONSE_PARAMETERS))
__AGY_RESPONSE_TEMPLATES= $(if $(AGY_METHODRESPONSE_RESPONSE_TEMPLATES), --response-templates $(AGY_METHODRESPONSE_RESPONSE_TEMPLATES))
__AGY_REST_API_ID__METHODRESPONSE= $(if $(AGY_METHODRESPONSE_RESTAPI_ID), --rest-api-id $(AGY_METHODRESPONSE_RESTAPI_ID))
__AGY_SELECTION_PATTERN= $(if $(AGY_METHODRESPONSE_SELECTION_PATTERN), --selection-pattern $(AGY_METHODRESPONSE_SELECTION_PATTERN))
__AGY_STATUS_CODE__METHODRESPONSE= $(if $(AGY_METHODRESPONSE_STATUS_CODE), --status-code $(AGY_METHODRESPONSE_STATUS_CODE))

# UI parameters

#--- MACROS

#----------------------------------------------------------------------
# USAGE
#
_agw_view_framework_macros ::
	@echo 'AWS::ApiGatewaY::MethodResponse ($(_AWS_APIGATEWAY_METHODRESPONSE_MK_VERSION)) macros:'
	@echo

_agw_view_framework_parameters ::
	@echo 'AWS::ApiGatewaY::MethodResponse ($(_AWS_APIGATEWAY_METHODRESPONSE_MK_VERSION)) parameters:'
	@echo '    AGY_METHODRESPONSE_CONTENT_HANDLING=$(AGY_METHODRESPONSE_CONTENT_HANDLING)'
	@echo '    AGY_METHODRESPONSE_HTTP_METHOD=$(AGY_METHODRESPONSE_HTTP_METHOD)'
	@echo '    AGY_METHODRESPONSE_NAME=$(AGY_METHODRESPONSE_NAME)'
	@echo '    AGY_METHODRESPONSE_PATCH_OPERATIONRESPONSES=$(AGY_METHODRESPONSE_PATCH_OPERATIONRESPONSES)'
	@echo '    AGY_METHODRESPONSE_RESOURCE_ID=$(AGY_METHODRESPONSE_RESOURCE_ID)'
	@echo '    AGY_METHODRESPONSE_RESOURCE_NAME=$(AGY_METHODRESPONSE_RESOURCE_NAME)'
	@echo '    AGY_METHODRESPONSE_RESPONSE_PARAMETERS=$(AGY_METHODRESPONSE_RESPONSE_PARAMETERS)'
	@echo '    AGY_METHODRESPONSE_RESPONSE_TEMPLATES=$(AGY_METHODRESPONSE_RESPONSE_TEMPLATES)'
	@echo '    AGY_METHODRESPONSE_RESTAPI_ID=$(AGY_METHODRESPONSE_RESTAPI_ID)'
	@echo '    AGY_METHODRESPONSE_RESTAPI_NAME=$(AGY_METHODRESPONSE_RESTAPI_NAME)'
	@echo '    AGY_METHODRESPONSE_SELECTION_PATTERN=$(AGY_METHODRESPONSE_SELECTION_PATTERN)'
	@echo '    AGY_METHODRESPONSE_STATUSCODE=$(AGY_METHODRESPONSE_STATUSCODE)'
	@echo '    AGY_METHODRESPONSES_SET_NAME=$(AGY_METHODRESPONSES_SET_NAME)'
	@echo

_agw_view_framework_targets ::
	@echo 'AWS::ApiGatewaY::MethodResponse ($(_AWS_APIGATEWAY_METHODRESPONSE_MK_VERSION)) targets:'
	@echo '    _agw_create_methodresponse                   - Create a new method-response'
	@echo '    _agw_delete_methodresponse                   - Delete an existing method-response'
	@echo '    _agw_show_methodresponse                     - Show everything related to a method-response'
	@echo '    _agw_show_methodresponse_description         - Show description of a method-response'
	@echo '    _agw_update_methodresponse                   - Update an method-response'
	@echo

#----------------------------------------------------------------------
# PRIVATE TARGETS
# 

#----------------------------------------------------------------------
# PUBLIC TARGETS
# 

_agw_create_methodresponse:
	@$(INFO) '$(AWS_UI_LABEL)Creating method-response "$(AGY_METHODRESPONSE_NAME)" ...'; $(NORMAL)
	$(AWS) apigateway put-method-response $(__AGY_HTTP_METHOD__METHODRESPONSE) $(__AGY_RESOURCE_ID__METHODRESPONSE) $(__AGY_RESPONSE_MODELS) $(__AGY_RESPONSE_PARAMETERS) $(__AGY_REST_API_ID__METHODRESPONSE) $(__AGY_STATUS_CODE__METHODRESPONSE)

_agw_delete_methodresponse:
	@$(INFO) '$(AWS_UI_LABEL)Deleting method-response "$(AGY_METHODRESPONSE_NAME)" ...'; $(NORMAL)
	$(AWS) apigateway delete-method-response $(__AGY_HTTP_METHOD__METHODRESPONSE) $(__AGY_RESOURCE_ID__METHODRESPONSE) $(__AGY_REST_API_ID__METHODRESPONSE) $(__AGY_STATUS_CODE__METHODRESPONSE)

_agw_show_methodresponse:: _agy_show_methodresponse_description

_agy_show_methodresponse_description:
	@$(INFO) '$(AWS_UI_LABEL)Showing description of method-response "$(AGY_METHODRESPONSE_NAME)" ...'; $(NORMAL)
	$(AWS) apigateway get-method-response $(__AGY_HTTP_METHOD__METHODRESPONSE) $(__AGY_RESOURCE_ID__METHODRESPONSE) $(__AGY_REST_API_ID__METHODRESPONSE) $(__AGY_STATUS_CODE__METHODRESPONSE)

_agw_update_methodresponse:
	@$(INFO) '$(AWS_UI_LABEL)Updating method-response "$(AGY_METHODRESPONSE_NAME)" ...'; $(NORMAL)
	$(AWS) apigateway update-method-response $(__AGY_HTTP_METHOD__METHODRESPONSE) $(__AGY_PATCH_OPERATION__METHODRESPONSE) $(__AGY_RESOURCE_ID__METHODRESPONSE) $(__AGY_REST_API_ID__METHODRESPONSE) $(__AGY_STATUS_CODE__METHODRESPONSE)
