_AWS_APIGATEWAY_INTEGRATIONRESPONSE_MK_VERSION= $(_AWS_APIGATEWAY_MK_VERSION)

# AGY_INTEGRATIONRESPONSE_CONTENT_HANDLING?=
# AGY_INTEGRATIONRESPONSE_HTTP_METHOD?=
# AGY_INTEGRATIONRESPONSE_NAME?=
# AGY_INTEGRATIONRESPONSE_PATCH_OPERATIONS?=
# AGY_INTEGRATIONRESPONSE_RESOURCE_ID?=
# AGY_INTEGRATIONRESPONSE_RESOURCE_NAME?=
# AGY_INTEGRATIONRESPONSE_RESPONSE_PARAMETERS?=
# AGY_INTEGRATIONRESPONSE_RESPONSE_TEMPLATES?=
# AGY_INTEGRATIONRESPONSE_RESTAPI_ID?=
# AGY_INTEGRATIONRESPONSE_RESTAPI_NAME?=
# AGY_INTEGRATIONRESPONSE_SELECTION_PATTERN?=
# AGY_INTEGRATIONRESPONSE_STATUSCODE?=
# AGY_INTEGRATIONRESPONSES_SET_NAME?= my-integration-responses-set

# Derived parameters
AGY_INTEGRATIONRESPONSE_NAME?= $(AGY_INTEGRATIONRESPONSE_RESTAPI_NAME):$(AGY_INTEGRATIONRESPONSE_RESOURCE_NAME):$(AGY_INTEGRATIONRESPONSE_HTTP_METHOD)
AGY_INTEGRATIONRESPONSE_RESOURCE_ID?= $(AGY_RESOURCE_ID)
AGY_INTEGRATIONRESPONSE_RESOURCE_NAME?= $(AGY_RESOURCE_NAME)
AGY_INTEGRATIONRESPONSE_RESTAPI_ID?= $(AGY_RESTAPI_ID)
AGY_INTEGRATIONRESPONSE_RESTAPI_NAME?= $(AGY_RESTAPI_NAME)

# Option parameters
__AGY_CONTENT_HANDLING__INTEGRATIONRESPONSE= $(if $(AGY_INTEGRATIONRESPONSE_CONTENT_HANDLING), --content-handling $(AGY_INTEGRATIONRESPONSE_CONTENT_HANDLING))
__AGY_HTTP_METHOD__INTEGRATIONRESPONSE= $(if $(AGY_INTEGRATIONRESPONSE_HTTP_METHOD), --http-method $(AGY_INTEGRATIONRESPONSE_HTTP_METHOD))
__AGY_PATCH_OPERATIONS__INTEGRATIONRESPONSE= $(if $(AGY_INTEGRATIONRESPONSE_PATCH_OPERATIONS), --patch-operations $(AGY_INTEGRATIONRESPONSE_PATCH_OPERATIONS))
__AGY_RESOURCE_ID__INTEGRATIONRESPONSE= $(if $(AGY_INTEGRATIONRESPONSE_RESOURCE_ID), --resource-id $(AGY_INTEGRATIONRESPONSE_RESOURCE_ID))
__AGY_RESPONSE_PARAMETERS= $(if $(AGY_INTEGRATIONRESPONSE_RESPONSE_PARAMETERS), --response-parameters $(AGY_INTEGRATIONRESPONSE_RESPONSE_PARAMETERS))
__AGY_RESPONSE_TEMPLATES= $(if $(AGY_INTEGRATIONRESPONSE_RESPONSE_TEMPLATES), --response-templates $(AGY_INTEGRATIONRESPONSE_RESPONSE_TEMPLATES))
__AGY_REST_API_ID__INTEGRATIONRESPONSE= $(if $(AGY_INTEGRATIONRESPONSE_RESTAPI_ID), --rest-api-id $(AGY_INTEGRATIONRESPONSE_RESTAPI_ID))
__AGY_SELECTION_PATTERN= $(if $(AGY_INTEGRATIONRESPONSE_SELECTION_PATTERN), --selection-pattern $(AGY_INTEGRATIONRESPONSE_SELECTION_PATTERN))
__AGY_STATUS_CODE__INTEGRATIONRESPONSE= $(if $(AGY_INTEGRATIONRESPONSE_STATUS_CODE), --status-code $(AGY_INTEGRATIONRESPONSE_STATUS_CODE))

# UI parameters

#--- MACROS

#----------------------------------------------------------------------
# USAGE
#
_agy_view_framework_macros ::
	@echo 'AWS::ApiGatewaY::IntegrationResponse ($(_AWS_APIGATEWAY_INTEGRATIONRESPONSE_MK_VERSION)) macros:'
	@echo

_agy_view_framework_parameters ::
	@echo 'AWS::ApiGatewaY::IntegrationResponse ($(_AWS_APIGATEWAY_INTEGRATIONRESPONSE_MK_VERSION)) parameters:'
	@echo '    AGY_INTEGRATIONRESPONSE_CONTENT_HANDLING=$(AGY_INTEGRATIONRESPONSE_CONTENT_HANDLING)'
	@echo '    AGY_INTEGRATIONRESPONSE_HTTP_METHOD=$(AGY_INTEGRATIONRESPONSE_HTTP_METHOD)'
	@echo '    AGY_INTEGRATIONRESPONSE_NAME=$(AGY_INTEGRATIONRESPONSE_NAME)'
	@echo '    AGY_INTEGRATIONRESPONSE_PATCH_OPERATIONS=$(AGY_INTEGRATIONRESPONSE_PATCH_OPERATIONS)'
	@echo '    AGY_INTEGRATIONRESPONSE_RESOURCE_ID=$(AGY_INTEGRATIONRESPONSE_RESOURCE_ID)'
	@echo '    AGY_INTEGRATIONRESPONSE_RESOURCE_NAME=$(AGY_INTEGRATIONRESPONSE_RESOURCE_NAME)'
	@echo '    AGY_INTEGRATIONRESPONSE_RESPONSE_PARAMETERS=$(AGY_INTEGRATIONRESPONSE_RESPONSE_PARAMETERS)'
	@echo '    AGY_INTEGRATIONRESPONSE_RESPONSE_TEMPLATES=$(AGY_INTEGRATIONRESPONSE_RESPONSE_TEMPLATES)'
	@echo '    AGY_INTEGRATIONRESPONSE_RESTAPI_ID=$(AGY_INTEGRATIONRESPONSE_RESTAPI_ID)'
	@echo '    AGY_INTEGRATIONRESPONSE_RESTAPI_NAME=$(AGY_INTEGRATIONRESPONSE_RESTAPI_NAME)'
	@echo '    AGY_INTEGRATIONRESPONSE_SELECTION_PATTERN=$(AGY_INTEGRATIONRESPONSE_SELECTION_PATTERN)'
	@echo '    AGY_INTEGRATIONRESPONSE_STATUSCODE=$(AGY_INTEGRATIONRESPONSE_STATUSCODE)'
	@echo '    AGY_INTEGRATIONRESPONSES_SET_NAME=$(AGY_INTEGRATIONRESPONSES_SET_NAME)'
	@echo

_agy_view_framework_targets ::
	@echo 'AWS::ApiGatewaY::IntegrationResponse ($(_AWS_APIGATEWAY_INTEGRATIONRESPONSE_MK_VERSION)) targets:'
	@echo '    _agy_create_integrationresponse                   - Create a new integration-response'
	@echo '    _agy_delete_integrationresponse                   - Delete an existing integration-response'
	@echo '    _agy_show_integrationresponse                     - Show everything related to an integration-response'
	@echo '    _agy_show_integrationresponse_description         - Show description of an integration-response'
	@echo '    _agy_update_integrationresponse                   - Update an integration-response'
	@echo

#----------------------------------------------------------------------
# PRIVATE TARGETS
# 

#----------------------------------------------------------------------
# PUBLIC TARGETS
# 

_agy_create_integrationresponse:
	@$(INFO) '$(AWS_UI_LABEL)Creating integration-response "$(AGY_INTEGRATIONRESPONSE_NAME)" ...'; $(NORMAL)
	$(AWS) apigateway put-integration-response $(__AGY_CONTENT_HANDLING__INTEGRATIONRESPONSE) $(__AGY_HTTP_METHOD__INTEGRATIONRESPONSE) $(__AGY_RESOURCE_ID__INTEGRATIONRESPONSE) $(__AGY_RESPONSE_PARAMETERS) $(__AGY_RESPONSE_TEMPLATES) $(__AGY_REST_API_ID__INTEGRATIONRESPONSE) $(__AGY_SELECTION_PATTERN) $(__AGY_STATUS_CODE__INTEGRATIONRESPONSE)

_agy_delete_integrationresponse:
	@$(INFO) '$(AWS_UI_LABEL)Deleting integration-response "$(AGY_INTEGRATIONRESPONSE_NAME)" ...'; $(NORMAL)
	$(AWS) apigateway delete-integration-response $(__AGY_HTTP_METHOD__INTEGRATIONRESPONSE) $(__AGY_RESOURCE_ID__INTEGRATIONRESPONSE) $(__AGY_REST_API_ID__INTEGRATIONRESPONSE)

_agy_show_integrationresponse:: _agy_show_integrationresponse_description

_agy_show_integrationresponse_description:
	@$(INFO) '$(AWS_UI_LABEL)Showing description of integration-response "$(AGY_INTEGRATIONRESPONSE_NAME)" ...'; $(NORMAL)
	$(AWS) apigateway get-integration-response $(__AGY_HTTP_METHOD__INTEGRATIONRESPONSE) $(__AGY_RESOURCE_ID__INTEGRATIONRESPONSE) $(__AGY_REST_API_ID__INTEGRATIONRESPONSE)

_agy_update_integrationresponse:
	@$(INFO) '$(AWS_UI_LABEL)Updating integration-response "$(AGY_INTEGRATIONRESPONSE_NAME)" ...'; $(NORMAL)
	$(AWS) apigateway update-integration-response $(__AGY_HTTP_METHOD__INTEGRATIONRESPONSE) $(__AGY_PATCH_OPERATIONS__INTEGRATIONRESPONSE) $(__AGY_RESOURCE_ID__INTEGRATIONRESPONSE) $(__AGY_REST_API_ID__INTEGRATIONRESPONSE) $(__AGY_STATUS_CODE__INTEGRATIONRESPONSE)
