_AWS_HISTORY_MK_VERSION= 0.99.6

# HTY_COMMAND_ID?= b09604f5-3d67-4f5c-99f0-0e673a13fc85
HTY_COMMAND_INDEX?= 1
# HTY_HISTORY_INCLUDE?=
HTY_HISTORY_FORMAT?= detailed
# HTY_HISTORY_INCLUDE?=
HTY_HISTORY_LENGTH?= 40
# HTY_MODE_INTERACTIVE?= true

# Derived parameters
HTY_MODE_INTERACTIVE?= $(CMN_MODE_INTERACTIVE)

# Option parameters
__HTY_|_CAT= $(if $(filter false, $(HTY_MODE_INTERACTIVE)), | cat)
__HTY_EXCLUDE= $(if $(HTY_COMMAND_EXCLUDE), --exclude $(HTY_COMMAND_EXCLUDE))
__HTY_FORMAT= $(if $(HTY_COMMAND_FORMAT), --format $(HTY_COMMAND_FORMAT))
__HTY_INCLUDE= $(if $(HTY_COMMAND_INCLUDE), --include $(HTY_COMMAND_INCLUDE))

# UI parameters

#--- Utilities

#--- MACROS
_hty_get_command_id= $(call _hty_get_command_id_I, $(HTY_COMMAND_INDEX))
_hty_get_command_id_I= $(shell $(AWS) history list | head -$(strip $(1)) | tail -1 | cut -f1 -d ' ')

#----------------------------------------------------------------------
# USAGE
#

_aws_view_framework_macros :: _hty_view_framework_macros
_hty_view_framework_macros ::
	@echo 'AWS::HisTorY ($(_AWS_HISTORY_MK_VERSION)) macros:'
	@echo '    _hty_get_command_id_{|I}     - Get the ID of a command (historyIndex)'
	@echo

_aws_view_framework_parameters :: _hty_view_framework_parameters
_hty_view_framework_parameters ::
	@echo 'AWS::HisTorY ($(_AWS_HISTORY_MK_VERSION)) parameters:'
	@echo '    HTY_COMMAND_ID=$(HTY_COMMAND_ID)'
	@echo '    HTY_COMMAND_INDEX=$(HTY_COMMAND_INDEX)'
	@echo '    HTY_COMMAND_EXCLUDE=$(HTY_COMMAND_EXCLUDE)'
	@echo '    HTY_COMMAND_FORMAT=$(HTY_COMMAND_FORMAT)'
	@echo '    HTY_COMMAND_INCLUDE=$(HTY_COMMAND_INCLUDE)'
	@echo '    HTY_HISTORY_LENGTH=$(HTY_HISTORY_LENGTH)'
	@echo '    HTY_MODE_INTERACTIVE=$(HTY_MODE_INTERACTIVE)'
	@echo

_aws_view_framework_targets :: _hty_view_framework_targets
_hty_view_framework_targets ::
	@echo 'AWS::HisTorY ($(_AWS_HISTORY_MK_VERSION)) targets:'
	@echo '    _hty_enable_history          - Enabling command-history'
	@echo '    _hty_show_command            - Show everything related to a command'
	@echo '    _hty_show_command_apicalls   - Show API-calls executed by command'
	@echo '    _hty_view_history            - View command-history'
	@echo 

#----------------------------------------------------------------------
# PRIVATE TARGETS
#

#----------------------------------------------------------------------
# PUBLIC TARGETS
#

_hty_enable_history:
	@$(INFO) '$(AWS_UI_LABEL)Enabling history for this profile "$(AWS_PROFILE)" ...'; $(NORMAL)
	$(AWS) configure set cli_history enabled

_hty_show_command: _hty_show_command_apicalls

_hty_show_command_apicalls:
	@$(INFO) '$(AWS_UI_LABEL)Showing API-calls generated by command "$(HTY_COMMAND_ID)"  ...'; $(NORMAL)
	$(AWS) history show $(HTY_COMMAND_ID) $(__HTY_EXCLUDE) $(__HTY_FORMAT) $(__HTY_INCLUDE) $(__HTY_|_CAT)

_hty_view_history:
	@$(INFO) '$(AWS_UI_LABEL)Viewing history ...'; $(NORMAL)
	@$(WARN) 'Each line represents a command. The most recent one is at the top'; $(NORMAL)
	$(AWS) history list | head -$(HTY_HISTORY_LENGTH)
	@$(WARN) 'Fields: (1) the command_id, (2) the UTC date, (3) the first argument, (4) the exit_code'; $(NORMAL)
	@$(WARN) 'UTC is PST time + 7h'; $(NORMAL)
