_AWS_APIGATEWAY_INTEGRATION_MK_VERSION= $(_AWS_APIGATEWAY_MK_VERSION)

# AGY_INTEGRATION_CACHE_NAMESPACE?=
# AGY_INTEGRATION_CACHEKEY_PARAMETERS?=
# AGY_INTEGRATION_CONNECTION_ID?=
# AGY_INTEGRATION_CONNECTION_TYPE?=
# AGY_INTEGRATION_CONTENT_HANDLING?=
# AGY_INTEGRATION_CREDENTIALS?=
# AGY_INTEGRATION_HTTP_METHOD?=
# AGY_INTEGRATION_INTEGRATIONHTTP_METHOD?=
# AGY_INTEGRATION_NAME?=
# AGY_INTEGRATION_PASSTHROUGH_BEHAVIOR?=
# AGY_INTEGRATION_PATCH_OPERATIONS?=
# AGY_INTEGRATION_REQUEST_PARAMETERS?=
# AGY_INTEGRATION_REQUEST_TEMPLATES?=
# AGY_INTEGRATION_RESOURCE_ID?=
# AGY_INTEGRATION_RESOURCE_NAME?=
# AGY_INTEGRATION_RESTAPI_ID?=
# AGY_INTEGRATION_RESTAPI_NAME?=
# AGY_INTEGRATION_TIMEOUT?=
# AGY_INTEGRATION_TYPE?= HTTP_PROXY
# AGY_INTEGRATION_URI?=
# AGY_INTEGRATIONS_SET_NAME?= my-integration-responses-set

# Derived parameters
AGY_INTEGRATION_NAME?= $(AGY_INTEGRATION_RESTAPI_NAME):$(AGY_INTEGRATION_RESOURCE_NAME):$(AGY_INTEGRATION_HTTP_METHOD)
AGY_INTEGRATION_RESOURCE_ID?= $(AGY_RESOURCE_ID)
AGY_INTEGRATION_RESOURCE_NAME?= $(AGY_RESOURCE_NAME)
AGY_INTEGRATION_RESTAPI_ID?= $(AGY_RESTAPI_ID)
AGY_INTEGRATION_RESTAPI_NAME?= $(AGY_RESTAPI_NAME)

# Option parameters
__AGY_CACHE_NAMESPACE= $(if $(AGY_INTEGRATION_CACHE_NAMESPACE), --cache-namespace $(AGY_INTEGRATION_CACHE_NAMESPACE))
__AGY_CACHE_KEY_PARAMETERS= $(if $(AGY_INTEGRATION_CACHEKEY_PARAMETERS), --cache-key-parameters $(AGY_INTEGRATION_CACHEKEY_PARAMETERS))
__AGY_CONNECTION_ID= $(if $(AGY_INTEGRATION_CONNECTION_ID), --connection-id $(AGY_INTEGRATION_CONNECTION_ID))
__AGY_CONNECTION_TYPE= $(if $(AGY_INTEGRATION_CONNECTION_TYPE), --connection-id $(AGY_INTEGRATION_CONNECTION_TYPE))
__AGY_CONTENT_HANDLING__INTEGRATION= $(if $(AGY_INTEGRATION_CONTENT_HANDLING), --content-handling $(AGY_INTEGRATION_CONTENT_HANDLING))
__AGY_CREDENTIALS= $(if $(AGY_INTEGRATION_CREDENTIALS), --credentials $(AGY_INTEGRATION_CREDENTIALS))
__AGY_HTTP_METHOD__INTEGRATION= $(if $(AGY_INTEGRATION_HTTP_METHOD), --http-method $(AGY_INTEGRATION_HTTP_METHOD))
__AGY_INTEGRATION_HTTP_METHOD= $(if $(AGY_INTEGRATION_INTEGRATIONHTTP_METHOD), --integration-http-method $(AGY_INTEGRATION_INTEGRATIONHTTP_METHOD))
__AGY_PASSTHROUGH_BEHAVIOR= $(if $(AGY_INTEGRATION_PASSTHROUGH_BEHAVIOR), --passthrough-behavior $(AGY_INTEGRATION_PASSTHROUGH_BEHAVIOR))
__AGY_PATCH_OPERATIONS__INTEGRATION= $(if $(AGY_INTEGRATION_PATCH_OPERATIONS), --patch-operations $(AGY_INTEGRATION_PATCH_OPERATIONS))
__AGY_POSITION__INTEGRATION=
__AGY_REQUEST_PARAMETERS= $(if $(AGY_INTEGRATION_REQUEST_PARAMETERS), --request-parameters $(AGY_INTEGRATION_REQUEST_PARAMETERS))
__AGY_REQUEST_TEMPLATES= $(if $(AGY_INTEGRATION_REQUEST_TEMPLATES), --request-templates $(AGY_INTEGRATION_REQUEST_TEMPLATES))
__AGY_RESOURCE_ID__INTEGRATION= $(if $(AGY_INTEGRATION_RESOURCE_ID), --resource-id $(AGY_INTEGRATION_RESOURCE_ID))
__AGY_REST_API_ID__INTEGRATION= $(if $(AGY_INTEGRATION_RESTAPI_ID), --rest-api-id $(AGY_INTEGRATION_RESTAPI_ID))
__AGY_TIMEOUT_IN_MILLIS= $(if $(AGY_INTEGRATION_TIMEOUT), --timeout-in-millis $(AGY_INTEGRATION_TIMEOUT))
__AGY_TYPE__INTEGRATION= $(if $(AGY_INTEGRATION_TYPE), --type $(AGY_INTEGRATION_TYPE))
__AGY_URI= $(if $(AGY_INTEGRATION_URI), --uri $(AGY_INTEGRATION_URI))

# UI parameters

#--- MACROS

#----------------------------------------------------------------------
# USAGE
#
_agy_view_framework_macros ::
	@echo 'AWS::ApiGatewaY::Integration ($(_AWS_APIGATEWAY_INTEGRATION_MK_VERSION)) macros:'
	@echo

_agy_view_framework_parameters ::
	@echo 'AWS::ApiGatewaY::Integration ($(_AWS_APIGATEWAY_INTEGRATION_MK_VERSION)) parameters:'
	@echo '    AGY_INTEGRATION_CACHE_NAMESPACE=$(AGY_INTEGRATION_CACHE_NAMESPACE)'
	@echo '    AGY_INTEGRATION_CACHEKEY_PARAMETERS=$(AGY_INTEGRATION_CACHEKEY_PARAMETERS)'
	@echo '    AGY_INTEGRATION_CONNECTION_ID=$(AGY_INTEGRATION_CONNECTION_ID)'
	@echo '    AGY_INTEGRATION_CONNECTION_TYPE=$(AGY_INTEGRATION_CONNECTION_TYPE)'
	@echo '    AGY_INTEGRATION_CONTENT_HANDLING=$(AGY_INTEGRATION_CONTENT_HANDLING)'
	@echo '    AGY_INTEGRATION_CREDENTIALS=$(AGY_INTEGRATION_CREDENTIALS)'
	@echo '    AGY_INTEGRATION_HTTP_METHOD=$(AGY_INTEGRATION_HTTP_METHOD)'
	@echo '    AGY_INTEGRATION_INTEGRATIONHTTP_METHOD=$(AGY_INTEGRATION_INTEGRATIONHTTP_METHOD)'
	@echo '    AGY_INTEGRATION_NAME=$(AGY_INTEGRATION_NAME)'
	@echo '    AGY_INTEGRATION_PASSTHROUGH_BEHAVIOR=$(AGY_INTEGRATION_PASSTHROUGH_BEHAVIOR)'
	@echo '    AGY_INTEGRATION_PATCH_OPERATIONS=$(AGY_INTEGRATION_PATCH_OPERATIONS)'
	@echo '    AGY_INTEGRATION_REQUEST_PARAMETERS=$(AGY_INTEGRATION_REQUEST_PARAMETERS)'
	@echo '    AGY_INTEGRATION_REQUEST_TEMPLATES=$(AGY_INTEGRATION_REQUEST_TEMPLATES)'
	@echo '    AGY_INTEGRATION_RESOURCE_ID=$(AGY_INTEGRATION_RESOURCE_ID)'
	@echo '    AGY_INTEGRATION_RESOURCE_NAME=$(AGY_INTEGRATION_RESOURCE_NAME)'
	@echo '    AGY_INTEGRATION_RESTAPI_ID=$(AGY_INTEGRATION_RESTAPI_ID)'
	@echo '    AGY_INTEGRATION_RESTAPI_NAME=$(AGY_INTEGRATION_RESTAPI_NAME)'
	@echo '    AGY_INTEGRATION_TIMEOUT=$(AGY_INTEGRATION_TIMEOUT)'
	@echo '    AGY_INTEGRATION_TYPE=$(AGY_INTEGRATION_TYPE)'
	@echo '    AGY_INTEGRATION_URI=$(AGY_INTEGRATION_URI)'
	@echo '    AGY_INTEGRATIONS_SET_NAME=$(AGY_INTEGRATIONS_SET_NAME)'
	@echo

_agy_view_framework_targets ::
	@echo 'AWS::ApiGatewaY::Integration ($(_AWS_APIGATEWAY_INTEGRATION_MK_VERSION)) targets:'
	@echo '    _agy_create_integration                   - Create a new integration'
	@echo '    _agy_delete_integration                   - Delete an existing integration'
	@echo '    _agy_show_integration                     - Show everything related to an integration'
	@echo '    _agy_update_integration                   - Update an integration'
	@echo

#----------------------------------------------------------------------
# PRIVATE TARGETS
# 

#----------------------------------------------------------------------
# PUBLIC TARGETS
# 

_agy_create_integration:
	@$(INFO) '$(AWS_UI_LABEL)Creating integration "$(AGY_INTEGRATION_NAME)" ...'; $(NORMAL)
	$(AWS) apigateway put-integration $(__AGY_CACHE_NAMESPACE) $(__AGY_CACHE_KEY_PARAMETERS) $(__AGY_CONNECTION_ID) $(__AGY_CONNECTION_TYPE) $(__AGY_CONTENT_HANDLING__INTEGRATION) $(__AGY_CREDENTIALS) $(__AGY_HTTP_METHOD__INTEGRATION) $(__AGY_INTEGRATION_HTTP_METHOD) $(__AGY_PASSTHROUGH_BEHAVIOR) $(__AGY_REQUEST_PARAMETERS) $(__AGY_REQUEST_TEMPLATES) $(__AGY_RESOURCE_ID__INTEGRATION) $(__AGY_REST_API_ID__INTEGRATION) $(__AGY_TIMEOUT_IN_MILLIS) $(__AGY_TYPE__INTEGRATION) $(__AGY_URI)

_agy_delete_integration:
	@$(INFO) '$(AWS_UI_LABEL)Deleting integration "$(AGY_INTEGRATION_NAME)" ...'; $(NORMAL)
	$(AWS) apigateway delete-integration $(__AGY_HTTP_METHOD__INTEGRATION) $(__AGY_RESOURCE_ID__INTEGRATION) $(__AGY_REST_API_ID__INTEGRATION)

_agy_show_integration:: _agy_show_integration_description

_agy_show_integration_description:
	@$(INFO) '$(AWS_UI_LABEL)Showing description of integration "$(AGY_INTEGRATION_NAME)" ...'; $(NORMAL)
	$(AWS) apigateway get-integration $(__AGY_HTTP_METHOD__INTEGRATION) $(__AGY_RESOURCE_ID__INTEGRATION) $(__AGY_REST_API_ID__INTEGRATION)

_agy_update_integration:
	@$(INFO) '$(AWS_UI_LABEL)Updating integration "$(AGY_INTEGRATION_NAME)" ...'; $(NORMAL)
	$(AWS) apigateway update-integration $(__AGY_HTTP_METHOD__INTEGRATION) $(__AGY_PATCH_OPERATIONS__INTEGRATION) $(__AGY_RESOURCE_ID__INTEGRATION) $(__AGY_REST_API_ID__INTEGRATION)
