_AWS_ECSCLI_TASKDEFINITION_MK_VERSION= $(_AWS_ECSCLI_MK_VERSION)

# ECI_TASKDEFINITION_ACCOUNT_ID?=
# ECI_TASKDEFINITION_ARN?=
# ECI_TASKDEFINITION_CLUSTER_NAME?=
ECI_TASKDEFINITION_CREATELOGGROUP_FLAG?= false
# ECI_TASKDEFINITION_DIRPATH?=
# ECI_TASKDEFINITION_DOCKERCOMPOSE_DIRPATH?= ./
ECI_TASKDEFINITION_DOCKERCOMPOSE_FILENAME?= docker-compose.yml
# ECI_TASKDEFINITION_DOCKERCOMPOSE_FILEPATH?= ./docker-compose.yml
# ECI_TASKDEFINITION_ECSPARAMS_DIRPATH?= ./
ECI_TASKDEFINITION_ECSPARAMS_FILENAME?= ecs-params.yml
# ECI_TASKDEFINITION_ECSPARAMS_FILEPATH?= ./ecs-params.yml
# ECI_TASKDEFINITION_FAMILY_NAME?=
# ECI_TASKDEFINITION_FILENAME?= task-definition.json
# ECI_TASKDEFINITION_LAUNCH_TYPE?= EC2
ECI_TASKDEFINITION_OUTPUT_FILENAME?= docker-compose.ecs-local.yml
# ECI_TASKDEFINITION_NAME?= family_name:2
# ECI_TASKDEFINITION_REGION_ID?= us-west-1
# ECI_TASKDEFINITION_REMOTE_ARN?= arn:aws:ecs:us-east-1:123456789012:task-definition/ec2:1
ECI_TASKDEFINITION_REVISION_ID?= 1
# ECI_TASKDEFINITION_TAGS_KEYVALUES?= Key=Value ...
# ECI_TASKDEFINITIONS_CLUSTER_NAME?=
# ECI_TASKDEFINITIONS_SET_NAME?=

# Derived parameters
ECI_TASKDEFINITION_ACCOUNT_ID?= $(ECI_ACCOUNT_ID)
ECI_TASKDEFINITION_ARN?= $(if $(ECI_TASKDEFINITION_NAME),arn:aws:ecs:$(ECI_TASKDEFINITION_REGION_ID):$(ECI_TASKDEFINITION_ACCOUNT_ID):task-definition/$(ECI_TASKDEFINITION_NAME))
ECI_TASKDEFINITION_CLUSTER_NAME?= $(ECI_CLUSTER_NAME)
ECI_TASKDEFINITION_DIRPATH?= $(ECI_INPUTS_DIRPATH)
ECI_TASKDEFINITION_DOCKERCOMPOSE_DIRPATH?= $(ECI_TASKDEFINITION_DIRPATH)
ECI_TASKDEFINITION_DOCKERCOMPOSE_FILEPATH?= $(ECI_TASKDEFINITION_DOCKERCOMPOSE_DIRPATH)$(ECI_TASKDEFINITION_DOCKERCOMPOSE_FILENAME)
ECI_TASKDEFINITION_ECSPARAMS_DIRPATH?= $(ECI_TASKDEFINITION_DIRPATH)
ECI_TASKDEFINITION_ECSPARAMS_FILEPATH?= $(ECI_TASKDEFINITION_ECSPARAMS_DIRPATH)$(ECI_TASKDEFINITION_ECSPARAMS_FILENAME)
ECI_TASKDEFINITION_FAMILY_NAME?= $(lastword $(subst /,$(SPACE), $(ECI_TASKDEFINITION_DIRPATH)))
ECI_TASKDEFINITION_LAUNCH_TYPE?= $(ECI_LAUNCH_TYPE)
ECI_TASKDEFINITION_NAME?= $(if $(ECI_TASKDEFINITION_FAMILY_NAME),$(ECI_TASKDEFINITION_FAMILY_NAME):$(ECI_TASKDEFINITION_REVISION_ID))
ECI_TASKDEFINITION_REGION_ID?= $(ECI_REGION_ID)
ECI_TASKDEFINITIONS_CLUSTER_NAME?= $(ECI_TASKDEFINITION_CLUSTER_NAME)

# Options parameters
__ECI_CLUSTER__TASKDEFINITION= $(if $(ECI_TASKDEFINITION_CLUSTER_NAME),--cluster $(ECI_TASKDEFINITION_CLUSTER_NAME))
__ECI_CLUSTER__TASKDEFINITIONS= $(if $(ECI_TASKDEFINITIONS_CLUSTER_NAME),--cluster $(ECI_TASKDEFINITIONS_CLUSTER_NAME))
__ECI_CREATE_LOG_GROUPS__TASKDEFINITION= $(if $(filter true, $(ECI_TASKDEFINITION_CREATELOGGROUP_FLAG)),--create-log-groups)
# __ECI_ECS_PARAMS= $(if $(ECI_TASKDEFINITION_ECSPARAMS_FILEPATH),--ecs-params $(ECI_TASKDEFINITION_ECSPARAMS_FILEPATH))
__ECI_ECS_PARAMS= $(if $(ECI_TASKDEFINITION_ECSPARAMS_FILENAME),--ecs-params $(ECI_TASKDEFINITION_ECSPARAMS_FILENAME))
# __ECI_FILE= $(if $(ECI_TASKDEFINITION_DOCKERCOMPOSE_FILEPATH),--file $(ECI_TASKDEFINITION_DOCKERCOMPOSE_FILEPATH))
__ECI_FILE= $(if $(ECI_TASKDEFINITION_DOCKERCOMPOSE_FILENAME),--file $(ECI_TASKDEFINITION_DOCKERCOMPOSE_FILENAME))
__ECI_LAUNCH_TYPE__TASKDEFINITION= $(if $(ECI_TASKDEFINITION_LAUNCH_TYPE),--launch-type $(ECI_TASKDEFINITION_LAUNCH_TYPE))
__ECI_OUTPUT__TASKDEFINITION= $(if $(ECI_TASKDEFINITION_OUTPUT_FILENAME),--output $(ECI_TASKDEFINITION_OUTPUT_FILENAME))
__ECI_TASK_DEF_FILE= $(if $(ECI_TASKDEFINITION_FILENAME),--task-def-file $(ECI_TASKDEFINITION_FILENAME))
__ECI_TASK_DEF_REMOTE= $(if $(ECI_TASKDEFINITION_REMOTE_ARN),--task-def-remote $(ECI_TASKDEFINITION_REMOTE_ARN))
__ECI_TASK_ROLE_ARN= $(if $(ECI_TASKDEFINITION_TASKROLE_ARN),--task-role-arn $(ECI_TASKDEFINITION_TASKROLE_ARN))
__ECI_TAGS__TASKDEFINITION= $(if $(ECI_TASKDEFINITION_TAGS_KEYVALUES),--tags $(ECI_TASKDEFINITION_TAGS_KEYVALUES))

# Pipe parameters

# UI parameters

#--- Utilities

#--- MACROS

#----------------------------------------------------------------------
# USAGE
#

_eci_view_framework_macros ::
	@echo 'AWS::EcsClI::TaskDefinition ($(_AWS_ECSCLI_TASKDEFINITION_MK_VERSION)) macros:'
	@echo

_eci_view_framework_parameters ::
	@echo 'AWS::EcsClI::TaskDefinition ($(_AWS_ECSCLI_TASKDEFINITION_MK_VERSION)) parameters:'
	@echo '    ECI_TASKDEFINITION_ACCOUNT_ID=$(ECI_TASKDEFINITION_ACCOUNT_ID)'
	@echo '    ECI_TASKDEFINITION_ARN=$(ECI_TASKDEFINITION_ARN)'
	@echo '    ECI_TASKDEFINITION_CLUSTER_NAME=$(ECI_TASKDEFINITION_CLUSTER_NAME)'
	@echo '    ECI_TASKDEFINITION_CREATELOGGROUP_FLAG=$(ECI_TASKDEFINITION_CREATELOGGROUP_FLAG)'
	@echo '    ECI_TASKDEFINITION_DIRPATH=$(ECI_TASKDEFINITION_DIRPATH)'
	@echo '    ECI_TASKDEFINITION_DOCKERCOMPOSE_DIRPATH=$(ECI_TASKDEFINITION_DOCKERCOMPOSE_DIRPATH)'
	@echo '    ECI_TASKDEFINITION_DOCKERCOMPOSE_FILENAME=$(ECI_TASKDEFINITION_DOCKERCOMPOSE_FILENAME)'
	@echo '    ECI_TASKDEFINITION_DOCKERCOMPOSE_FILEPATH=$(ECI_TASKDEFINITION_DOCKERCOMPOSE_FILEPATH)'
	@echo '    ECI_TASKDEFINITION_ECSPARAMS_DIRPATH=$(ECI_TASKDEFINITION_ECSPARAMS_DIRPATH)'
	@echo '    ECI_TASKDEFINITION_ECSPARAMS_FILENAME=$(ECI_TASKDEFINITION_ECSPARAMS_FILENAME)'
	@echo '    ECI_TASKDEFINITION_ECSPARAMS_FILEPATH=$(ECI_TASKDEFINITION_ECSPARAMS_FILEPATH)'
	@echo '    ECI_TASKDEFINITION_FAMILY_NAME=$(ECI_TASKDEFINITION_FAMILY_NAME)'
	@echo '    ECI_TASKDEFINITION_FILENAME=$(ECI_TASKDEFINITION_FILENAME)'
	@echo '    ECI_TASKDEFINITION_LAUNCH_TYPE=$(ECI_TASKDEFINITION_LAUNCH_TYPE)'
	@echo '    ECI_TASKDEFINITION_NAME=$(ECI_TASKDEFINITION_NAME)'
	@echo '    ECI_TASKDEFINITION_OUTPUT_FILENAME=$(ECI_TASKDEFINITION_OUTPUT_FILENAME)'
	@echo '    ECI_TASKDEFINITION_REGION_ID=$(ECI_TASKDEFINITION_REGION_ID)'
	@echo '    ECI_TASKDEFINITION_REMOTE_ARN=$(ECI_TASKDEFINITION_REMOTE_ARN)'
	@echo '    ECI_TASKDEFINITION_REVISION_ID=$(ECI_TASKDEFINITION_REVISION_ID)'
	@echo '    ECI_TASKDEFINITION_TAGS_KEYVALUES=$(ECI_TASKDEFINITION_TAGS_KEYVALUES)'
	@echo '    ECI_TASKDEFINITIONS_CLUSTER_NAME=$(ECI_TASKDEFINITIONS_CLUSTER_NAME)'
	@echo '    ECI_TASKDEFINITIONS_SET_NAME=$(ECI_TASKDEFINITIONS_SET_NAME)'
	@echo

_eci_view_framework_targets ::
	@echo 'AWS::EcsClI::TaskDefinition ($(_AWS_ECSCLI_TASKDEFINITION_MK_VERSION)) targets:'
	@echo '    _eci_convert_taskdefinition                 - Convert an existing task-definition to docker-compose'
	@echo '    _eci_create_taskdefinition                  - Create a new task-definition'
	@echo '    _eci_delete_taskdefinition                  - Delete an existing task-definition'
	@echo '    _eci_show_taskdefinition                    - Show everything related to a task-definition'
	@echo '    _eci_show_taskdefinition_description        - Show the description of a task-definition'
	@echo '    _eci_view_taskdefinitions                   - View task-definitions'
	@echo '    _eci_view_taskdefinitions_set               - View a set of task-definitions'
	@echo

#----------------------------------------------------------------------
# PRIVATE TARGETS
#

#----------------------------------------------------------------------
# PUBLIC TARGETS
#

_eci_convert_taskdefinition:
	@$(INFO) '$(ECI_UI_LABEL)Convert to docker-compose the task-definition "$(ECI_TASKDEFINITION_NAME)" ...'; $(NORMAL)
	@$(WARN) 'This operation outputs 2 files, one is the docker compose'; $(NORMAL)
	cd $(ECI_TASKDEFINITION_DIRPATH) && $(ECSCLI) local create $(_X__ECI_AWS_PROFILE) $(__ECI_OUTPUT__TASKDEFINITION) $(__ECI_TASK_DEF_FILE) $(_X__ECI_TASK_DEF_REMOTE) 

_eci_create_taskdefinition:
	@$(INFO) '$(ECI_UI_LABEL)Creating task-definition "$(ECI_TASKDEFINITION_NAME)" ...'; $(NORMAL)
	@$(WARN) 'This operation fails if --create-log-groups is provided and the log-group already exists'; $(NORMAL)
	@# Note sure why, but I cannot specifiy the --ecs-params and --file 
	@$(WARN) 'Docker-compose file'; $(NORMAL)
	$(if $(ECI_TASKDEFINITION_DOCKERCOMPOSE_FILEPATH), cat $(ECI_TASKDEFINITION_DOCKERCOMPOSE_FILEPATH))
	@$(WARN) 'ECS-params file'; $(NORMAL)
	$(if $(ECI_TASKDEFINITION_ECSPARAMS_FILEPATH), cat $(ECI_TASKDEFINITION_ECSPARAMS_FILEPATH))
	cd $(ECI_TASKDEFINITION_DIRPATH) && $(ECSCLI) compose create $(strip $(__ECI_AWS_PROFILE) $(__ECI_CLUSTER__TASKDEFINITION) $(__ECI_CREATE_LOG_GROUPS__TASKDEFINITION) $(__ECI_LAUNCH_TYPE__TASKDEFINITION) $(__ECI_REGION) $(__ECI_TAGS__TASKDEFINITION) $(_X__ECI_ECS_PARAMS) $(_X__ECI_FILE) $(__ECI_REGION) $(__ECI_TASK_ROLE_ARN) )

_eci_delete_taskdefinition:
	@$(INFO) '$(ECI_UI_LABEL)Deleting task-definition "$(ECI_TASKDEFINITION_NAME)" ...'; $(NORMAL)

_eci_show_taskdefinition :: _eci_show_taskdefinition_dockercompose _eci_show_taskdefinition_ecsparams _eci_show_taskdefinition_description

_eci_show_taskdefinition_description: 
	@$(INFO) '$(ECI_UI_LABEL)Showing description of task-definition "$(ECI_TASKDEFINITION_NAME)" ...'; $(NORMAL)
	ls -la $(ECI_TASKDEFINITION_DOCKERCOMPOSE_FILEPATH) $(ECI_TASKDEFINITION_ECSPARAMS_FILEPATH)

_eci_show_taskdefinition_dockercompose:
	@$(INFO) '$(ECI_UI_LABEL)Showing docker-compose of task-definition "$(ECI_TASKDEFINITION_NAME)" ...'; $(NORMAL)
	cat $(ECI_TASKDEFINITION_DOCKERCOMPOSE_FILEPATH)

_eci_show_taskdefinition_ecsparams:
	@$(INFO) '$(ECI_UI_LABEL)Showing ecs-params of task-definition "$(ECI_TASKDEFINITION_NAME)" ...'; $(NORMAL)
	cat $(ECI_TASKDEFINITION_ECSPARAMS_FILEPATH)

_eci_view_taskdefinitions:
	@$(INFO) '$(ECI_UI_LABEL)Viewing task-definitions ...'; $(NORMAL)
	$(ECSCLI) ps $(__ECI_AWS_PROFILE) $(__ECI_CLUSTER__TASKS)

_eci_view_taskdefinitions_set:
	@$(INFO) '$(ECI_UI_LABEL)Viewing task-definitions-set "$(ECI_TASKDEFINITIONS_SET_NAME)" ...'; $(NORMAL)
