_AZ_ROLE_ROLEASSIGNMENT_MK_VERSION= $(_AZ_ROLE_MK_VERSION)

# RLE_ROLEASSIGNMENT_ASSIGNEE?=
# RLE_ROLEASSIGNMENT_ASSIGNEE_OBJECTID?=
# RLE_ROLEASSIGNMENT_ASSIGNEE_PRINCIPALTYPE?= User
# RLE_ROLEASSIGNMENT_ID?= 5a8dffba-83a4-42ce-8b75-620dc1172f55
# RLE_ROLEASSIGNMENT_NAME?= my-role-assignment
# RLE_ROLEASSIGNMENT_RESOURCEGROUP_NAME?=
# RLE_ROLEASSIGNMENT_ROLE_NAME?= "Storage Account Key Operator Service Role"
# RLE_ROLEASSIGNMENT_SCOPE?= /subscriptions/0b1f6471-1bf0-4dda-aec3-111122223333 
# RLE_ROLEASSIGNMENTS_RESOURCEGROUP_NAME?=
# RLE_ROLEASSIGNMENTS_ROLE_NAME?= "Storage Account Key Operator Service Role"
# RLE_ROLEASSIGNMENTS_SCOPE?= /subscriptions/0b1f6471-1bf0-4dda-aec3-111122223333
# RLE_ROLEASSIGNMENTS_SET_NAME?= my-role-assignments-set

# Derived parameters
# RLE_ROLEASSIGNMENT_RESOURCEGROUP_NAME?= $(RLE_RESOURCEGROUP_NAME)# Use the resource-group scope instaed?
RLE_ROLEASSIGNMENT_ROLE_NAME?= $(RLE_ROLE_NAME)
# RLE_ROLEASSIGNMENTS_RESOURCEGROUP_NAME?= $(RLE_ROLEASSIGNMENT_RESOURCEGROUP_NAME)# Use the resource-group scope instead?
RLE_ROLEASSIGNMENTS_ROLE_NAME?= $(RLE_ROLEASSIGNMENT_ROLE_NAME)
RLE_ROLEASSIGNMENTS_SCOPE?= $(RLE_ROLEASSIGNMENT_SCOPE)

# Options parameters
__RLE_ALL__ROLEASSIGNMENTS=
__RLE_ASSIGNEE__ROLEASSIGNMENT= $(if $(RLE_ROLEASSIGNMENT_ASSIGNEE),--assignee $(RLE_ROLEASSIGNMENT_ASSIGNEE))
__RLE_ASSIGNEE__ROLEASSIGNMENTS= $(if $(RLE_ROLEASSIGNMENTS_ASSIGNEE),--assignee $(RLE_ROLEASSIGNMENTS_ASSIGNEE))
__RLE_ASSIGNEE_OBJECT_ID__ROLEASSIGNMENT= $(if $(RLE_ROLEASSIGNMENT_ASSIGNEE_OBJECTID),--assignee-object-id $(RLE_ROLEASSIGNMENT_ASSIGNEE_OBJECTID))
__RLE_ASSIGNEE_PRINCIPAL_TYPE__ROLEASSIGNMENT= $(if $(RLE_ROLEASSIGNMENT_ASSIGNEE_PRINCIPALTYPE),--assignee-principal-type $(RLE_ROLEASSIGNMENT_ASSIGNEE_PRINCIPALTYPE))
__RLE_IDS__ROLEASSIGNMENT=
__RLE_INCLUDE_CLASSIC_ADMINISTRATORS=
__RLE_INCLUDE_GROUPS=
__RLE_INCLUDE_INHERITED__ROLEASSIGNMENT=
__RLE_INCLUDE_INHERITED__ROLEASSIGNMENTS=
__RLE_NAME__ROLEASSIGNMENT= $(if $(RLE_ROLEASSIGNMENT_NAME),--name $(RLE_ROLEASSIGNMENT_NAME))
__RLE_RESOURCE_GROUP__ROLEASSIGNMENT= $(if $(RLE_ROLEASSIGNMENT_RESOURCEGROUP_NAME),--resource-group $(RLE_ROLEASSIGNMENT_RESOURCEGROUP_NAME))
__RLE_RESOURCE_GROUP__ROLEASSIGNMENTS= $(if $(RLE_ROLEASSIGNMENTS_RESOURCEGROUP_NAME),--resource-group $(RLE_ROLEASSIGNMENTS_RESOURCEGROUP_NAME))
# __RLE_OUTPUT?=
__RLE_ROLE__ROLEASSIGNMENT= $(if $(RLE_ROLEASSIGNMENT_ROLE_NAME),--role $(RLE_ROLEASSIGNMENT_ROLE_NAME))
__RLE_ROLE__ROLEASSIGNMENTS= $(if $(RLE_ROLEASSIGNMENTS_ROLE_NAME),--role $(RLE_ROLEASSIGNMENTS_ROLE_NAME))
__RLE_SCOPE__ROLEASSIGNMENT= $(if $(RLE_ROLEASSIGNMENT_SCOPE),--scope $(RLE_ROLEASSIGNMENT_SCOPE))
__RLE_SCOPE__ROLEASSIGNMENTS= $(if $(RLE_ROLEASSIGNMENTS_SCOPE),--scope $(RLE_ROLEASSIGNMENTS_SCOPE))
__RLE_YES=

# UI parameters
RLE_UI_SHOW_ROLEASSIGNMENT_FIELDS?= .{name:name,principalName:principalName,resourceGroup:resourceGroup,roleDefinitionName:roleDefinitionName}
RLE_UI_SHOW_ROLEASSIGNMENT_QUERYFILTER?= ?name=='$(RLE_ROLEASSIGNMENT_ID)'
RLE_UI_VIEW_ROLEASSIGNMENTS_FIELDS?= .{name:name,principalType:principalType,roleDefinitionName:roleDefinitionName,principalName:principalName,resourceGroup:resourceGroup}
RLE_UI_VIEW_ROLEASSIGNMENTS_SET_FIELDS?= $(RLE_UI_VIEW_ROLEASSIGNMENTS_FIELDS)
RLE_UI_VIEW_ROLEASSIGNMENTS_SET_QUERYFILTER?=

#--- Utilities

#--- MACRO

#----------------------------------------------------------------------
# USAGE
#

_rle_view_framework_macros ::
	@#echo 'AZ::RoLE::RoleAssignment ($(_AZ_ROLE_ROLEASSIGNMENT_MK_VERSION)) macros:'
	@#echo

_rle_view_framework_parameters ::
	@echo 'AZ::RoLE::RoleAssignment ($(_AZ_ROLE_ROLEASSIGNMENT_MK_VERSION)) parameters:'
	@echo '    RLE_ROLEASSIGNMENT_ASSIGNEE=$(RLE_ROLEASSIGNMENT_ASSIGNEE)'
	@echo '    RLE_ROLEASSIGNMENT_ASSIGNEE_OBJECTID=$(RLE_ROLEASSIGNMENT_ASSIGNEE_OBJECTID)'
	@echo '    RLE_ROLEASSIGNMENT_ASSIGNEE_PRINCIPALTYPE=$(RLE_ROLEASSIGNMENT_ASSIGNEE_PRINCIPALTYPE)'
	@echo '    RLE_ROLEASSIGNMENT_ID=$(RLE_ROLEASSIGNMENT_ID)'
	@echo '    RLE_ROLEASSIGNMENT_NAME=$(RLE_ROLEASSIGNMENT_NAME)'
	@echo '    RLE_ROLEASSIGNMENT_RESOURCEGROUP_NAME=$(RLE_ROLEASSIGNMENT_RESOURCEGROUP_NAME)'
	@echo '    RLE_ROLEASSIGNMENT_ROLE_NAME=$(RLE_ROLEASSIGNMENT_ROLE_NAME)'
	@echo '    RLE_ROLEASSIGNMENT_SCOPE=$(RLE_ROLEASSIGNMENT_SCOPE)'
	@echo '    RLE_ROLEASSIGNMENTS_RESOURCEGROUP_NAME=$(RLE_ROLEASSIGNMENTS_RESOURCEGROUP_NAME)'
	@echo '    RLE_ROLEASSIGNMENTS_ROLE_NAME=$(RLE_ROLEASSIGNMENTS_ROLE_NAME)'
	@echo '    RLE_ROLEASSIGNMENTS_SCOPE=$(RLE_ROLEASSIGNMENTS_SCOPE)'
	@echo '    RLE_ROLEASSIGNMENTS_SET_NAME=$(RLE_ROLEASSIGNMENTS_SET_NAME)'
	@echo

_rle_view_framework_targets ::
	@echo 'AZ::RoLE::RoleAssignment ($(_AZ_ROLE_ROLEASSIGNMENT_MK_VERSION)) targets:'
	@echo '    _rle_create_roleassignment             - Create a role-assignment'
	@echo '    _rle_delete_roleassignment             - Delete a role-assignment'
	@echo '    _rle_show_roleassignment               - Show everything related to a role-assignment'
	@echo '    _rle_show_roleassignment_description   - Show description of a role-assignment'
	@echo '    _rle_show_roleassignment_object        - Show object of a role-assignment'
	@echo '    _rle_view_roleassignments              - View role-assignments'
	@echo '    _rle_view_roleassignments_set          - View set of role-assignments'
	@echo

#----------------------------------------------------------------------
# PRIVATE TARGETS
#

#----------------------------------------------------------------------
# PUBLIC TARGETS
#

_rle_create_roleassignment:
	@$(INFO) '$(RLE_UI_LABEL)Creating role-assignment "$(RLE_ROLEASSIGNMENT_NAME)" ...'; $(NORMAL)
	$(AZ) role assignment create $(__RLE_ASSIGNEE__ROLEASSIGNMENT) $(__RLE_ASSIGNEE_OBJECT_ID) $(__RLE_ASSIGNEE_PRINCIPAL_TYPE) $(__RLE_OUTPUT) $(__RLE_RESOURCE_GROUP__ROLEASSIGNMENT) $(__RLE_ROLE__ROLEASSIGNMENT) $(__RLE_SCOPE__ROLEASSIGNMENT) $(__RLE_SUBSCRIPTION)

_rle_delete_roleassignment:
	@$(INFO) '$(RLE_UI_LABEL)Deleting role-assignment "$(RLE_ROLEASSIGNMENT_NAME)" ...'; $(NORMAL)
	$(AZ) role assignment delete $(__RLE_ASSIGNEE__ROLEASSIGNMENT) $(__RLE_IDS__ROLEASSIGNMENT) $(__RLE_INCLUDE_INHERITED__ROLEASSIGNMENT) $(__RLE_OUTPUT) $(__RLE_RESOURCE_GROUP__ROLEASSIGNMENT) $(__RLE_ROLE__ROLEASSIGNMENT) $(__RLE_SCOPE__ROLEASSIGNMENT) $(__RLE_SUBSCRIPTION) $(__RLE_YES)

_rle_show_roleassignment :: _rle_show_roleassignment_object _rle_show_roleassignment_description

_rle_show_roleassignment_description:
	@$(INFO) '$(RLE_UI_LABEL)Showing description of role-assignment "$(RLE_ROLEASSIGNMENT_NAME)" ...'; $(NORMAL)
	$(AZ) role assignment list $(_X__RLE_ALL__ROLEASSIGNMENT) --all $(_X__RLE_ASSIGNEE__ROLEASSIGNMENT) $(_X__RLE_INCLUDE_CLASSIC_ADMINISTRATORS) $(__RLE_INCLUDE_GROUPS) $(__RLE_INCLUDE_INHERITED__ROLEASSIGNMENT) $(__RLE_OUTPUT) $(_X__RLE_RESOURCE_GROUP__ROLEASSIGNMENT) $(_X__RLE_SCOPE__ROLEASSIGNMENT) $(__RLE_SUBSCRIPTION) --query "[$(RLE_UI_SHOW_ROLEASSIGNMENT_QUERYFILTER)]$(RLE_UI_SHOW_ROLEASSIGNMENT_FIELDS)"

_rle_show_roleassignment_object:
	@$(INFO) '$(RLE_UI_LABEL)Showing object of role-assignment "$(RLE_ROLEASSIGNMENT_NAME)" ...'; $(NORMAL)
	$(AZ) role assignment list $(_X__RLE_ALL__ROLEASSIGNMENT) --all $(_X__RLE_ASSIGNEE__ROLEASSIGNMENT) $(_X__RLE_INCLUDE_CLASSIC_ADMINISTRATORS) $(__RLE_INCLUDE_GROUPS) $(__RLE_INCLUDE_INHERITED__ROLEASSIGNMENT) $(_X__RLE_OUTPUT) --output json $(_X__RLE_RESOURCE_GROUP__ROLEASSIGNMENT) $(_X__RLE_SCOPE__ROLEASSIGNMENT) $(__RLE_SUBSCRIPTION) --query "[$(RLE_UI_SHOW_ROLEASSIGNMENT_QUERYFILTER)]"

_rle_view_roleassignments:
	@$(INFO) '$(RLE_UI_LABEL)Viewing role-assignments ...'; $(NORMAL)
	$(AZ) role assignment list $(_X__RLE_ALL__ROLEASSIGNMENTS) --all $(_X__RLE_ASSIGNEE__ROLEASSIGMENTS) $(__RLE_INCLUDE_CLASSIC_ADMINISTRATORS) $(__RLE_INCLUDE_GROUPS) $(__RLE_INCLUDE_INHERITED__ROLEASSIGNMENTS) $(__RLE_OUTPUT) $(_X__RLE_RESOURCE_GROUP__ROLEASSIGNMENTS) $(_X__RLE_SCOPE__ROLEASSIGNMENTS) $(__RLE_SUBSCRIPTION) --query "[]$(RLE_UI_VIEW_ROLEASSIGNMENTS_FIELDS)"

_rle_view_roleassignments_set:
	@$(INFO) '$(RLE_UI_LABEL)Viewing role-assignments-set "$(RLE_ROLEASSIGNMENTS_SET_NAME) ...'; $(NORMAL)
	@$(WARN) 'Role-assignments are grouped based on assignee, resource-group, scope, and query-filter'; $(NORMAL)
	$(AZ) role assignment list $(_X__RLE_ALL__ROLEASSIGNMENTS) $(__RLE_ASSIGNEE__ROLEASSIGMENTS) $(__RLE_INCLUDE_CLASSIC_ADMINISTRATORS) $(__RLE_INCLUDE_GROUPS) $(__RLE_INCLUDE_INHERITED__ROLEASSIGNMENTS) $(__RLE_OUTPUT) $(__RLE_RESOURCE_GROUP__ROLEASSIGNMENTS) $(__RLE_SCOPE__ROLEASSIGNMENTS) $(__RLE_SUBSCRIPTION) --query "[$(RLE_UI_VIEW_ROLEASSIGNMENTS_SET_QUERYFILTER)]$(RLE_UI_VIEW_ROLEASSIGNMENTS_SET_FIELDS)"
