_AZ_VMS_SCALESET_MK_VERSION= $(_AZ_VMS_MK_VERSION)

# VMS_SCALESET_ADMIN_PASSWORD?=
# VMS_SCALESET_ADMIN_USER?=
# VMS_SCALESET_AUTHENTICATION_TYPE?= all
# VMS_SCALESET_COMPUTERNAME_PREFIX?= computer
# VMS_SCALESET_ID?=
# VMS_SCALESET_IDENTITY_NAME?=
# VMS_SCALESET_IMAGE_NAME?=
# VMS_SCALESET_INSTANCE_COUNT?= 1
# VMS_SCALESET_INSTANCE_ID?=
# VMS_SCALESET_LOCATION_ID?= westus2
# VMS_SCALESET_NAME?= MyScaleset
VMS_SCALESET_NOWAIT_FLAG?= false
# VMS_SCALESET_OS_TYPE?= linux
# VMS_SCALESET_RESOURCEGROUP_NAME?= MyResourceGroup
# VMS_SCALESETS_IDS?=
# VMS_SCALESETS_RESOURCEGROUP_NAME?= MyResourceGroup
# VMS_SCALESETS_SSHPUBLICKEY_FILEPATH?=
# VMS_SCALESETS_SET_NAME?=

# Derived parameters
VMS_SCALESET_LOCATION_ID?= $(VMS_LOCATION_ID)
VMS_SCALESET_RESOURCEGROUP_NAME?= $(VMS_RESOURCEGROUP_NAME)
VMS_SCALESET_SUBSCRIPTION_ID?= $(VMS_SUBSCRIPTION_ID)
VMS_SCALESETS_RESOURCEGROUP_NAME?= $(VMS_SCALESET_RESOURCEGROUP_NAME)

# Options parameters
__VMS_ACCELERATED_NETWORKING=
__VMS_ADMIN_PASSWORD= $(if $(VMS_SCALESET_ADMIN_PASSWORD),--admin-password $(VMS_SCALESET_ADMIN_PASSWORD))
__VMS_ADMIN_USERNAME= $(if $(VMS_SCALESET_ADMIN_USERNAME),--admin-username $(VMS_SCALESET_ADMIN_USERNAME))
__VMS_APP_GATEWAY=
__VMS_APP_GATEWAY_CAPACITY=
__VMS_APP_GATEWAY_SKU=
__VMS_APP_GATEWAY_SUBNET_ADDRESS_PREFIX=
__VMS_ASGS=
__VMS_ASSIGN_IDENTITY= $(if $(VMS_SCALESET_IDENTITY_NAME),--assign-identity $(VMS_SCALESET_IDENTITY_NAME))
__VMS_AUTHENTICATION_TYPE= $(if $(VMS_SCALESET_AUTHENTICATION_TYPE),--authentication-type $(VMS_SCALESET_AUTHENTICATION_TYPE))
__VMS_BACKEND_POOL_NAME=
__VMS_BACKEND_PORT=
__VMS_COMPUTERNAME_PREFIX= $(if $(VMS_SCALESET_COMPUTERNAME_PREFIX),--computer-name-prefix $(VMS_SCALESET_COMPUTERNAME_PREFIX))
__VMS_CUSTOM_DATA=
__VMS_DATA_DISK_CACHING=
__VMS_DATA_DISK_SIZES_GB=
__VMS_DISABLE_OVERPROVISION=
__VMS_DNS_SERVERS=
__VMS_EPHERMERAL_OS_DISK=
__VMS_EVICTION_POLICY=
__VMS_GENERATE_SSH_KEYS=
__VMS_HEALTH_PROBE=
__VMS_IDS__SCALESET= $(if $(VMS_SCALESET_ID),--ids $(VMS_SCALESET_ID))
__VMS_IDS__SCALESETS= $(if $(VMS_SCALESETS_IDS),--ids $(VMS_SCALESETS_IDS))
__VMS_IMAGE= $(if $(VMS_SCALESET_IMAGE_NAME),--image $(VMS_SCALESET_IMAGE_NAME))
__VMS_INSTANCE_COUNT= $(if $(VMS_SCALESET_INSTANCE_COUNT),--instance-count $(VMS_SCALESET_INSTANCE_COUNT))
__VMS_INSTANCE_ID= $(if $(VMS_SCALESET_INSTANCE_ID),--instance-id $(VMS_SCALESET_INSTANCE_ID))
__VMS_LB=
__VMS_LB_NAT_POOL_NAME=
__VMS_LB_SKU=
__VMS_LICENSE_TYPE=
__VMS_LOCATION__SCALESET= $(if $(VMS_SCALESET_LOCATION_ID),--location $(VMS_SCALESET_LOCATION_ID))
__VMS_MAX_PRICE=
__VMS_NAME__SCALESET= $(if $(VMS_SCALESET_NAME),--name $(VMS_SCALESET_NAME))
__VMS_NO_WAIT__SCALESET= $(if $(filter true, $(VMS_SCALESET_NOWAIT_FLAG)),--no-wait)
__VMS_NSG=
__VMS_ORCHESTRATION_MODE=
__VMS_OS_DISK_CACHING=
__VMS_OS_DISK_NAME=
__VMS_OS_TYPE= $(if $(VMS_SCALESET_OS_TYPE),--os-type $(VMS_SCALESET_OS_TYPE))
__VMS_PLAN_NAME=
__VMS_PLAN_PRODUCT=
__VMS_PLAN_PROMOTION_CODE=
__VMS_PLAN_PUBLISHER=
__VMS_PLATFORM_FAULT_DOMAIN_COUNT=
__VMS_PPG=
__VMS_PRIORITY=
__VMS_PUBLIC_IP_ADDRESS=
__VMS_PUBLIC_IP_ADDRESS_ALLOCATION=
__VMS_PUBLIC_IP_ADDRESS_DNS_NAME=
__VMS_PUBLIC_IP_PER_VM=
__VMS_RESOURCE_GROUP__SCALESET= $(if $(VMS_SCALESET_RESOURCEGROUP_NAME),--resource-group $(VMS_SCALESET_RESOURCEGROUP_NAME))
__VMS_RESOURCE_GROUP__SCALESETS= $(if $(VMS_SCALESETS_RESOURCEGROUP_NAME),--resource-group $(VMS_SCALESETS_RESOURCEGROUP_NAME))
__VMS_ROLE=
__VMS_SCOPE=
__VMS_SECRETS=
__VMS_SINGLE_PLACEMENT_GROUP=
__VMS_SSH_DEST_KEY_PATH=
__VMS_SSH_KEY_VALUES= $(if $(VMS_SCALESET_SSHPUBLICKEY_FILEPATH),--ssh-key-values @$(VMS_SCALESET_SSHPUBLICKEY_FILEPATH))
__VMS_STORAGE_CONTAINER_NAME=
__VMS_STORAGE_SKU=
__VMS_SUBNET=
__VMS_SUBNET_ADDRESS_PREFIX=
__VMS_TAGS=
__VMS_TERMINATE_NOTIFICATION_TIME==
__VMS_ULTRA_SSD_ENABLED=
__VMS_UPGRADE_POLICY_MODE=
__VMS_USE_UNMANAGED_DISK=
__VMS_VALIDATE=
__VMS_VM_DOMAIN_NAME=
__VMS_VM_SKU=
__VMS_VNET_ADDRESS_PREFIX=
__VMS_VNET_NAME=
__VMS_ZONE=

# UI parameters

#--- Utilities

#--- MACRO

#----------------------------------------------------------------------
# USAGE
#

_vms_view_framework_macros ::
	@echo 'AZ::VM::ScaleSet ($(_AZ_VMS_SCALESET_MK_VERSION)) macros:'
	@echo

_vms_view_framework_parameters ::
	@echo 'AZ::VM::ScaleSet ($(_AZ_VMS_SCALESET_MK_VERSION)) parameters:'
	@echo '    VMS_SCALESET_ADMIN_PASSWORD=$(VMS_SCALESET_ADMIN_PASSWORD)'
	@echo '    VMS_SCALESET_ADMIN_USERNAME=$(VMS_SCALESET_ADMIN_USERNAME)'
	@echo '    VMS_SCALESET_AUTHENTICATION_TYPE=$(VMS_SCALESET_AUTHENTICATION_TYPE)'
	@echo '    VMS_SCALESET_COMPUTERNAME_PREFIX=$(VMS_SCALESET_COMPUTERNAME_PREFIX)'
	@echo '    VMS_SCALESET_ID=$(VMS_SCALESET_ID)'
	@echo '    VMS_SCALESET_IDENTITY_NAME=$(VMS_SCALESET_IDENTITY_NAME)'
	@echo '    VMS_SCALESET_IMAGE_NAME=$(VMS_SCALESET_IMAGE_NAME)'
	@echo '    VMS_SCALESET_INSTANCE_COUNT=$(VMS_SCALESET_INSTANCE_COUNT)'
	@echo '    VMS_SCALESET_INSTANCE_ID=$(VMS_SCALESET_INSTANCE_ID)'
	@echo '    VMS_SCALESET_LOCATION_ID=$(VMS_SCALESET_LOCATION_ID)'
	@echo '    VMS_SCALESET_NAME=$(VMS_SCALESET_NAME)'
	@echo '    VMS_SCALESET_NOWAIT_FLAG=$(VMS_SCALESET_NOWAIT_FLAG)'
	@echo '    VMS_SCALESET_OS_TYPE=$(VMS_SCALESET_OS_TYPE)'
	@echo '    VMS_SCALESET_RESOURCEGROUP_NAME=$(VMS_SCALESET_RESOURCEGROUP_NAME)'
	@echo '    VMS_SCALESET_SSHPUBLICKEY_FILEPATH=$(VMS_SCALESET_SSHPUBLICKEY_FILEPATH)'
	@echo '    VMS_SCALESETS_RESOURCEGROUP_NAME=$(VMS_SCALESETS_RESOURCEGROUP_NAME)'
	@echo '    VMS_SCALESETS_SET_NAME=$(VMS_SCALESETS_SET_NAME)'
	@echo

_vms_view_framework_targets ::
	@echo 'AZ::VM::ScaleSet ($(_AZ_VMS_SCALESET_MK_VERSION)) targets:'
	@#echo '    _vms_create_scaleset                - Create an scaleset'
	@#echo '    _vms_delete_scaleset                - Delete an scaleset'
	@#echo '    _vms_show_scaleset                  - Show everything related to an scaleset'
	@#echo '    _vms_show_scaleset_description      - Show description of an scaleset'
	@echo '    _vms_view_scalesets                 - View scalesets'
	@#echo '    _vms_view_scalesets_set             - View a set of scalesets'
	@echo

#----------------------------------------------------------------------
# PRIVATE TARGETS
#

#----------------------------------------------------------------------
# PUBLIC TARGETS
#

_vms_create_scaleset:
	@$(INFO) '$(VMS_UI_LABEL)Creating scaleset "$(VMS_SCALESET_NAME)" ...'; $(NORMAL)
	$(AZ) vmss create $(strip $(__VMS_ACCELERATED_NETWORKING) $(__VMS_ADMIN_PASSWORD) $(__VMS_ADMIN_USERNAME) $(__VMS_APP_GATEWAY) $(__VMS_APP_GATEWAY_CAPACITY) $(__VMS_APP_GATEWAY_SKU) $(__VMS_APP_GATEWAY_SUBNET_ADDRESS_PREFIX) $(__VMS_ASGS) $(__VMS_ASSIGN_IDENTITY) i$(__VMS_AUTHENTICATION_TYPE) $(__VMS_BACKEND_POOL_NAME) $(__VMS_BACKEND_PORT) $(__VMS_COMPUTER_NAME_PREFIX) $(__VMS_CUSTOM_DATA) $(__VMS_DATA_DISK_CACHING) $(__VMS_DATA_DISK_SIZED_GB) $(__VMS_DISABLE_OVERPROVISION) $(__VMS_DNS_SERVERS) $(__VMS_EPHEMERAL_OS_DISK) $(__VMS_EVICTION_POLICY) $(__VMS_GENERATE_SSH_KEYS) $(__VMS_HEALTH_PROBE) $(__VMS_IMAGE) $(__VMS_INSTANCE_COUNT) i$(__VMS_LB) $(__VMS_LB_NAT_POOL_NAME) $(__VMS_LB_SKU) $(__VMS_LICENSE_TYPE) $(__VMS_LOCATION__SCALESET) $(__VMS_MAX_PRICE) $(__VMS_NAME__SCALESET) $(__VMS_NO_WAIT) $(__VMS_NSG) $(__VMS_ORCHESTRATION_MODE) $(__VMS_OS_DISK_CACHING) $(__VMS_OS_DISK_NAME) $(__VMS_OS_TYPE) $(__VMS_PLAN_NAME) $(__VMS_PLAN_PRODUCT) $(__VMS_PLAN_PROMOTION_CODE) $(__VMS_PLAN_PUBLISHER) $(__VMS_PLATFORM_FAULT_DOMAIN_COUNT) $(__VMS_PPG) $(__VMS_PRIORITY) $(__VMS_PUBLIC_IP_ADDRESS) $(__VMS_PUBLIC_IP_ADDRESS_ALLOCATION) $(__VMS_PUBLIC_IP_ADDRESS_DNS_NAME) $(__VMS_PUBLIC_IP_PER_VM) $(__VMS_RESOURCE_GROUP__SCALESET) $(__VMS_ROLE) $(__VMS_SCOPE) $(__VMS_SECRETS) $(__VMS_SINGLE_PLACEMENT_GROUP) $(__VMS_SSH_DEST_KEY_PATH) $(__VMS_SSH_KEY_VALUE) $(__VMS_STORAGE_CONTAINER_NAME) $(__VMS_STORAGE_SKU) $(__VMS_SUBNET) $(__VMS_SUBNET_ADDRESS_PREFIX) $(__VMS_SUBSCRIPTION) $(__VMS_TAGS__SCALESET) $(__VMS_TERMINATE_NOTIFICATION_TIME) $(__VMS_ULTRA_SSD_ENABLED) $(__VMS_USE_UNMANAGED_DISK) $(__VMS_VALIDATE) $(__VMS_VM_DOMAIN_NAME) $(__VMS_VM_SKU) $(__VMS_VNET_ADDRESS_PREFIX) $(__VMS_VNET_NAME) $(__VMS_ZONE))

_vms_delete_scaleset:
	@$(INFO) '$(VMS_UI_LABEL)Deleting scaleset "$(VMS_SCALESET_NAME)" ...'; $(NORMAL)
	$(AZ) vmss delete $(__VMS_IDS__SCALESET) $(__VMS_NAME__SCALESET) $(__VMS_NO_WAIT__SCALESET) $(__VMS_RESOURCE_GROUP__SCALESET) $(__VMS_SUBSCRIPTION)

_vms_show_scaleset :: _vms_show_scaleset_object _vms_show_scaleset_description

_vms_show_scaleset_description:
	@$(INFO) '$(VMS_UI_LABEL)Showing description of scaleset "$(VMS_SCALESET_NAME)" ...'; $(NORMAL)
	$(AZ) vmss show $(__VMS_INSTANCE_ID) $(__VMS_NAME__SCALESET) $(__VMS_OUTPUT) $(__VMS_RESOURCE_GROUP__SCALESET) $(__VMS_SUBSCRIPTION)

_vms_show_scaleset_object:
	@$(INFO) '$(VMS_UI_LABEL)Showing object of scaleset "$(VMS_SCALESET_NAME)" ...'; $(NORMAL)
	$(AZ) vmss show $(__VMS_INSTANCE_ID) $(__VMS_NAME__SCALESET) $(_X__VMS_OUTPUT) --output json $(__VMS_RESOURCE_GROUP__SCALESET) $(__VMS_SUBSCRIPTION)

_vms_view_scalesets:
	@$(INFO) '$(VMS_UI_LABEL)Viewing scalesets ...'; $(NORMAL)
	$(AZ) vmss list $(__VMS_OUTPUT) $(_X__VMS_RESOURCE_GROUP__SCALESETS) $(__VMS_SUBSCRIPTION)

_vms_view_scalesets_set:
	@$(INFO) '$(VMS_UI_LABEL)Viewing scalesets-set "$(VMS_SCALESETS_SET_NAME)" ...'; $(NORMAL)
	@$(WARN) 'Instances are grouped based on provided resource-group and query-filter'; $(NORMAL)
	#$(AZ) vmss list $(__VMS_OUTPUT) $(__VMS_RESOURCE_GROUP__SCALESETS) $(__VMS_SUBSCRIPTION) 
