_GITLAB_PROJECTPIPELINESCHEDULEVARIABLE_MK_VERSION= $(_GITLAB_MK_VERSION)

# GLB_PROJECTPIPELINESCHEDULEVARIABLE_ID?= 123456 
# GLB_PROJECTPIPELINESCHEDULEVARIABLE_NAME?= my-pipeline -schedule
# GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECT_ID?= 123456
# GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECT_NAME?= my-project
# GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECTPIPELINESCHEDULE_ID?= 123456
# GLB_PROJECTPIPELINESCHEDULEVARIABLE_VALUE?= value
# GLB_PROJECTPIPELINESCHEDULEVARIABLES_NAMEVALUES?= VAR1=my-var VAR2=my-var2
# GLB_PROJECTPIPELINESCHEDULEVARIABLES_PROJECT_ID?= 123456
# GLB_PROJECTPIPELINESCHEDULEVARIABLES_PROJECT_NAME?= my-project
# GLB_PROJECTPIPELINESCHEDULEVARIABLES_PROJECTPIPELINESCHEDULE_ID?= 123456
# GLB_PROJECTPIPELINESCHEDULEVARIABLES_PROJECTPIPELINESCHEDULE_NAME?= my-pipeline-schedule

# Derived parameters
GLB_PROJECTPIPELINESCHEDULEVARIABLE_NAME?= $(GLB_PROJECTPIPELINESCHEDULEVARIABLE_ID)
GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECT_ID?= $(GLB_PROJECT_ID)
GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECT_NAME?= $(GLB_PROJECT_NAME)
GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECTPIPELINESCHEDULE_ID?= $(GLB_PROJECTPIPELINESCHEDULE_ID)
GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECTPIPELINESCHEDULE_NAME?= $(GLB_PROJECTPIPELINESCHEDULE_NAME)
GLB_PROJECTPIPELINESCHEDULEVARIABLES_PROJECT_ID?= $(GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECT_ID)
GLB_PROJECTPIPELINESCHEDULEVARIABLES_PROJECT_NAME?= $(GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECT_NAME)
GLB_PROJECTPIPELINESCHEDULEVARIABLES_PROJECTPIPELINESCHEDULE_ID?= $(GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECTPIPELINESCHEDULE_ID)
GLB_PROJECTPIPELINESCHEDULEVARIABLES_PROJECTPIPELINESCHEDULE_NAME?= $(GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECTPIPELINESCHEDULE_NAME)

# Option parameters
__GLB_ID__PROJECTPIPELINESCHEDULEVARIABLES= $(if $(GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECTPIPELINESCHEDULE_ID),--id $(GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECTPIPELINESCHEDULE_ID))
__GLB_KEY= $(if $(GLB_PROJECTPIPELINESCHEDULEVARIABLE_NAME),--key $(GLB_PROJECTPIPELINESCHEDULEVARIABLE_NAME))
__GLB_PIPELINE_SCHEDULE_ID__PROJECTPIPELINESCHEDULEVARIABLE= $(if $(GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECTPIPELINESCHEDULE_ID),--pipeline-schedule-id $(GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECTPIPELINESCHEDULE_ID))
__GLB_PROJECT_ID__PROJECTPIPELINESCHEDULEVARIABLE= $(if $(GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECT_ID),--project-id $(GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECT_ID))
__GLB_PROJECT_ID__PROJECTPIPELINESCHEDULEVARIABLES= $(if $(GLB_PROJECTPIPELINESCHEDULEVARIABLES_PROJECT_ID),--project-id $(GLB_PROJECTPIPELINESCHEDULEVARIABLES_PROJECT_ID))
__GLB_VALUE= $(if $(GLB_PROJECTPIPELINESCHEDULEVARIABLE_VALUE),--value $(GLB_PROJECTPIPELINESCHEDULEVARIABLE_VALUE))

# UI parameters

#--- Utilities

#--- MACROS

#----------------------------------------------------------------------
# USAGE
#

_glb_view_framework_macros ::
	@echo 'GitLaB::ProjectPipelineScheduleVariable ($(_GITLAB_PROJECTPIPELINESCHEDULEVARIABLE_MK_VERSION)) macros:'
	@echo

_glb_view_framework_parameters ::
	@echo 'GitLaB::ProjectPipelineScheduleVariable ($(_GITLAB_PROJECTPIPELINESCHEDULEVARIABLE_MK_VERSION)) parameters:'
	@echo '    GLB_PROJECTPIPELINESCHEDULEVARIABLE_ID=$(GLB_PROJECTPIPELINESCHEDULEVARIABLE_ID)'
	@echo '    GLB_PROJECTPIPELINESCHEDULEVARIABLE_NAME=$(GLB_PROJECTPIPELINESCHEDULEVARIABLE_NAME)'
	@echo '    GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECT_ID=$(GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECT_ID)'
	@echo '    GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECT_NAME=$(GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECT_NAME)'
	@echo '    GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECTPIPELINESCHEDULE_ID=$(GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECTPIPELINESCHEDULE_ID)'
	@echo '    GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECTPIPELINESCHEDULE_NAME=$(GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECTPIPELINESCHEDULE_NAME)'
	@echo '    GLB_PROJECTPIPELINESCHEDULEVARIABLE_VALUE=$(GLB_PROJECTPIPELINESCHEDULEVARIABLE_VALUE)'
	@echo '    GLB_PROJECTPIPELINESCHEDULEVARIABLES_NAMEVALUES=$(GLB_PROJECTPIPELINESCHEDULEVARIABLES_NAMEVALUES)'
	@echo '    GLB_PROJECTPIPELINESCHEDULEVARIABLES_PROJECT_ID=$(GLB_PROJECTPIPELINESCHEDULEVARIABLES_PROJECT_ID)'
	@echo '    GLB_PROJECTPIPELINESCHEDULEVARIABLES_PROJECT_NAME=$(GLB_PROJECTPIPELINESCHEDULEVARIABLES_PROJECT_NAME)'
	@echo '    GLB_PROJECTPIPELINESCHEDULEVARIABLES_PROJECTPIPELINESCHEDULE_ID=$(GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECTPIPELINESCHEDULE_ID)'
	@echo '    GLB_PROJECTPIPELINESCHEDULEVARIABLES_PROJECTPIPELINESCHEDULE_NAME=$(GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECTPIPELINESCHEDULE_NAME)'
	@echo

_glb_view_framework_targets ::
	@echo 'GitLaB::ProjectPipelineScheduleVariable ($(_GITLAB_PROJECTPIPELINESCHEDULEVARIABLE_MK_VERSION)) targets:'
	@echo '    _glb_create_projectpipelineschedulevariable    - create a project-pipeline-schedule-variable'
	@echo '    _glb_create_projectpipelineschedulevariables   - create several project-pipeline-schedule-variables'
	@echo '    _glb_delete_projectpipelineschedulevariable    - delete a project-pipeline-schedule-variable'
	@echo '    _glb_delete_projectpipelineschedulevariables   - delete several project-pipeline-schedule-variables'
	@echo '    _glb_show_projectpipelineschedulevariable      - show a project-pipeline-schedule-variable'
	@echo '    _glb_update_projectpipelineschedulevariable    - update a project-pipeline-schedule-variable'
	@echo '    _glb_view_projectpipelineschedulevariables     - view project-pipeline-schedule-variables'
	@echo


#-----------------------------------------------------------------------
# PRIVATE TARGETS
#

#-----------------------------------------------------------------------
# PUBLIC TARGETS
#

_glb_create_projectpipelineschedulevariable:
	@$(INFO) '$(GLB_UI_LABEL)Creating a project-pipeline-schedule-variable "$(GLB_PROJECTPIPELINESCHEDULEVARIABLE_NAME)" ...'; $(NORMAL)
	$(GITLAB) project-pipeline-schedule-variable create $(__GLB_KEY) $(__GLB_PIPELINE_SCHEDULE_ID__PROJECTPIPELINESCHEDULEVARIABLE) $(__GLB_PROJECT_ID__PROJECTPIPELINESCHEDULEVARIABLE) $(__GLB_VALUE)

_glb_create_projectpipelineschedulevariables:
	@$(INFO) '$(GLB_UI_LABEL)Creating a project-pipeline-schedule-variables for "$(GLB_PROJECTPIPELINESCHEDULEVARIABLES_PROJECTPIPELINESCHEDULE_NAME)" ...'; $(NORMAL)
	$(foreach NV, $(GLB_PROJECTPIPELINESCHEDULEVARIABLES_NAMEVALUES),\
	$(GITLAB) project-pipeline-schedule-variable create --key $(firstword $(subst =,$(SPACE),$(NV))) $(__GLB_PIPELINE_SCHEDULE_ID__PROJECTPIPELINESCHEDULEVARIABLE) $(__GLB_PROJECT_ID__PROJECTPIPELINESCHEDULEVARIABLE) --value $(lastword $(subst =,$(SPACE),$(NV))); \
	)

_glb_delete_projectpipelineschedulevariable:
	@$(INFO) '$(GLB_UI_LABEL)Deleting a project-pipeline-schedule "$(GLB_PROJECTPIPELINESCHEDULEVARIABLE_NAME)" ...'; $(NORMAL)
	$(GITLAB) project-pipeline-schedule-variable delete $(__GLB_KEY) $(__GLB_PIPELINE_SCHEDULE_ID__PROJECTPIPELINESCHEDULEVARIABLE) $(__GLB_PROJECT_ID__PROJECTPIPELINESCHEDULEVARIABLE)

_glb_delete_projectpipelineschedulevariables:
	@$(INFO) '$(GLB_UI_LABEL)Deleting a project-pipeline-schedule-variables for "$(GLB_PROJECTPIPELINESCHEDULEVARIABLES_PROJECTPIPELINESCHEDULE_NAME)" ...'; $(NORMAL)
	$(foreach NV, $(GLB_PROJECTPIPELINESCHEDULEVARIABLES_NAMEVALUES),\
	$(GITLAB) project-pipeline-schedule-variable delete --key $(firstword $(subst =,$(SPACE),$(NV))) $(__GLB_PIPELINE_SCHEDULE_ID__PROJECTPIPELINESCHEDULEVARIABLE) $(__GLB_PROJECT_ID__PROJECTPIPELINESCHEDULEVARIABLE); \
	)

_glb_show_projectpipelineschedulevariable: 
	@$(INFO) '$(GLB_UI_LABEL)Showing variable "$(GLB_PROJECTPIPELINESCHEDULEVARIABLE_NAME)" of project-pipeline-schedule "$(GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECTPIPELINESCHEDULE_NAME)" ...'; $(NORMAL)
	$(GITLAB) project-pipeline-schedule get $(__GLB_ID__PROJECTPIPELINESCHEDULEVARIABLES) $(__GLB_PROJECT_ID__PROJECTPIPELINESCHEDULEVARIABLES) | sed '1,/variables:/ d'

_glb_update_projectpipelineschedulevariable:
	@$(INFO) '$(GLB_UI_LABEL)Updating variable "$(GLB_PROJECTPIPELINESCHEDULEVARIABLE_NAME)" of project-pipeline-schedule "$(GLB_PROJECTPIPELINESCHEDULEVARIABLE_PROJECTPIPELINESCHEDULE_NAME)" ...'; $(NORMAL)

_glb_view_projectpipelineschedulevariables:
	@$(INFO) '$(GLB_UI_LABEL)Viewing variables of project-pipeline-schedule "$(GLB_PROJECTPIEPELINESCHEDULEVARIABLES_PROJECTPIPELINESCHEDULE_NAME)" ...'; $(NORMAL)
	$(GITLAB) project-pipeline-schedule get $(__GLB_ID__PROJECTPIPELINESCHEDULEVARIABLES) $(__GLB_PROJECT_ID__PROJECTPIPELINESCHEDULEVARIABLES) | sed '1,/variables:/ d'
