_LOCUST_RUNNER_MK_VERSION= $(_LOCUST_MK_VERSION)

# LCT_RUNNER_CLIENTS_COUNT?= 2
# LCT_RUNNER_CLIENTS_HATCHRATE?= 5
# LCT_RUNNER_HOST_URL?= http://www.google.com
LCT_RUNNER_LOCUSTFILE_FILEPATH?= ./locustfile.py
# LCT_RUNNER_LOGS_FILEPATH?= ./locust.log
LCT_RUNNER_LOGS_LEVEL?= INFO
# LCT_RUNNER_MASTER?= true
# LCT_RUNNER_MASTER_BINDHOST?= *
# LCT_RUNNER_MASTER_BINDPORT?= 5557
# LCT_RUNNER_MASTER_BINDPORT?= 5557
LCT_RUNNER_NAME?= GrassHopper
# LCT_RUNNER_REPORT_ONLYSUMMARY?= true
# LCT_RUNNER_RUN_TIME?= 1h30m
# LCT_RUNNER_SLAVE?= true
# LCT_RUNNER_SLAVE_MASTERHOST?= 127.0.0.1
# LCT_RUNNER_SLAVE_MASTERPORT?= 5557
LCT_RUNNER_WEBHOST?= ''
# LCT_RUNNER_WEBHOST_PORT?= ''

# Derived variables

# Option variables
__LCT_CLIENTS= $(if $(LCT_RUNNER_CLIENTS_COUNT),--clients $(LCT_RUNNER_CLIENTS_COUNT))
__LCT_CVS=
__LCT_EXPECT_SLAVES=
__LCT_HATCH_RATE= $(if $(LCT_RUNNER_CLIENTS_HATCHRATE),--hatch-rate $(LCT_RUNNER_CLIENTS_HATCHRATE))
__LCT_HOST= $(if $(LCT_RUNNER_HOST_URL),--host $(LCT_RUNNER_HOST_URL))
__LCT_LOCUSTFILE= $(if $(LCT_RUNNER_LOCUSTFILE_FILEPATH),--locustfile $(LCT_RUNNER_LOCUSTFILE_FILEPATH))
__LCT_LOGFILE= $(if $(LCT_RUNNER_LOGS_FILEPATH),--logfile $(LCT_RUNNER_LOGS_FILEPATH))
__LCT_LOGLEVEL= $(if $(LCT_RUNNER_LOGS_LEVEL),--loglevel $(LCT_RUNNER_LOGS_LEVEL))
__LCT_MASTER= $(if $(true, $(LCT_RUNNER_MASTER)),--master)
__LCT_MASTER_BIND_HOST= $(if $(LCT_RUNNER_MASTER_BINDHOST),--master-bind-host $(LCT_RUNNER_MASTER_BIND_HOST))
__LCT_MASTER_BIND_PORT= $(if $(LCT_RUNNER_MASTER_BINDPORT),--master-bind-port $(LCT_RUNNER_MASTER_BIND_PORT))
__LCT_MASTER_HOST= $(if $(LCT_RUNNER_SLAVE_MASTERHOST),--master-host $(LCT_RUNNER_SLAVE_MASTERHOST))
__LCT_MASTER_PORT= $(if $(LCT_RUNNER_SLAVE_MASTERPORT),--master-port $(LCT_RUNNER_SLAVE_MASTERPORT))
__LCT_NO_WEB= $(if $(LCT_RUNNER_WEBHOST),,--no-web)
__LCT_NUM_REQUEST=
__LCT_ONLY_SUMMARY= $(if $(filter true, $(LCT_RUNNER_REPORT_ONLYSUMMARY)),--only-summary)
__LCT_PORT= $(if $(LCT_RUNNER_WEBHOST_PORT),--port $(LCT_RUNNER_WEBHOST_PORT))
__LCT_PRINT_STATS=
__LCT_RESET_STATS=
__LCT_RUN_TIME= $(if $(LCT_RUNNER_RUN_TIME),--run-time $(LCT_RUNNER_RUN_TIME))
__LCT_SLAVE= $(if $(true, $(LCT_RUNNER_SLAVE)),--slave)
__LCT_WEB_HOST= $(if $(LCT_RUNNER_WEBHOST),--web-host $(LCT_RUNNER_WEBHOST))

# UI variables
 
#--- Utilities

#--- MACROS

#----------------------------------------------------------------------
# USAGE
#

_lct_view_framework_macros ::
	@#echo 'Locust::Runner ($(_LOCUST_RUNNER_MK_VERSION)) macros:'
	@#echo

_lct_view_framework_parameters ::
	@echo 'Locust::Runner ($(_LOCUST_RUNNER_MK_VERSION)) parameters:'
	@echo '    LCT_RUNNER_CLIENTS_COUNT=$(LCT_RUNNER_CLIENTS_COUNT)'
	@echo '    LCT_RUNNER_CLIENTS_HATCHRATE=$(LCT_RUNNER_CLIENTS_HATCHRATE)'
	@echo '    LCT_RUNNER_HOST_URL=$(LCT_RUNNER_HOST_URL)'
	@echo '    LCT_RUNNER_LOCUSFILE_FILEPATH=$(LCT_RUNNER_LOCUSTFILE_FILEPATH)'
	@echo '    LCT_RUNNER_LOGS_FILEPATH=$(LCT_RUNNER_LOGS_FILEPATH)'
	@echo '    LCT_RUNNER_LOGS_LEVEL=$(LCT_RUNNER_LOGS_LEVEL)'
	@echo '    LCT_RUNNER_MASTER=$(LCT_RUNNER_MASTER)'
	@echo '    LCT_RUNNER_MASTER_BINDHOST=$(LCT_RUNNER_MASTER_BINDHOST)'
	@echo '    LCT_RUNNER_MASTER_BINDPORT=$(LCT_RUNNER_MASTER_BINDPORT)'
	@echo '    LCT_RUNNER_REPORT_SUMMARYONLY=$(LCT_RUNNER_REPORT_SUMMARYONLY)'
	@echo '    LCT_RUNNER_RUN_TIME=$(LCT_RUNNER_RUN_TIME)'
	@echo '    LCT_RUNNER_SLAVE=$(LCT_RUNNER_SLAVE)'
	@echo '    LCT_RUNNER_SLAVE_MASTERHOST=$(LCT_RUNNER_SLAVE_MASTERHOST)'
	@echo '    LCT_RUNNER_SLAVE_MASTERPORT=$(LCT_RUNNER_SLAVE_MASTERPORT)'
	@echo '    LCT_RUNNER_WEBHOST=$(LCT_RUNNER_WEBHOST)'
	@echo '    LCT_RUNNER_WEBHOST_PORT=$(LCT_RUNNER_WEBHOST_PORT)'
	@echo

_lct_view_framework_targets ::
	@echo 'Locust::Runner ($(_LOCUST_RUNNER_MK_VERSION)) targets:'
	@echo '    _lct_create_runner             - Create a runner'
	@echo

#-----------------------------------------------------------------------
# PRIVATE TARGETS
#

#-----------------------------------------------------------------------
# PUBLIC TARGETS
#

_lct_create_runner:
	@$(INFO) '$(LCT_UI_LABEL)Creating runner "$(LCT_RUNNER_NAME)" ...'; $(NORMAL)
	$(LOCUST) $(strip $(__LCT_CLIENTS) $(__LCT_CSV) $(__LCT_EXPECT_SLAVES) $(__LCT_HATCH_RATE) $(__LCT_HOST) $(__LCT_LOCUSTFILE) $(__LCT_LOGFILE) $(__LCT_LOGLEVEL) $(__LCT_MASTER) $(__LCT_MASTER_BIND_HOST) $(__LCT_MASTER_BIND_PORT) $(__LCT_MASTER_HOST) $(__LCT_MASTER_PORT) $(__LCT_NO_WEB) $(__LCT_NUM_REQUEST) $(__LCT_ONLY_SUMMARY) $(__LCT_PORT) $(__LCT_PRINT_STATS) $(__LCT_RESET_STATS) $(__LCT_RUN_TIME) $(__LCT_SLAVE) $(__LCT_WEB_HOST) )
