_SCP_REMOTEUSER_MK_VERSION= $(_SCP_MK_VERSION)

# SCP_REMOTEUSER?=
# SCP_REMOTEUSER_CONFIG_DIRPATH?= $(HOME)/.ssh/
# SCP_REMOTEUSER_CONFIG_FILENAME?= config
# SCP_REMOTEUSER_CONFIG_FILEPATH?= $(HOME)/.ssh/config
SCP_REMOTEUSER_HOST_IP?= 127.0.0.1
SCP_REMOTEUSER_HOST_NAME?= localhost
# SCP_REMOTEUSER_HOST_IP_OR_NAME?=
# SCP_REMOTEUSER_HOST_PORT?= 22
# SCP_REMOTEUSER_LOCALSOURCE_DIRPATH?= ./in/
# SCP_REMOTEUSER_LOCALSOURCE_FILENAME?= script.sh
# SCP_REMOTEUSER_LOCALSOURCE_FILEPATH?= ./in/script.sh
# SCP_REMOTEUSER_NAME?= ubuntu@localhost
SCP_REMOTEUSER_PRESERVE_FLAG?= false
SCP_REMOTEUSER_PRIVATEKEY_FILEPATH?= $(HOME)/.ssh/id_rsa
SCP_REMOTEUSER_PUBLICKEY_FILEPATH?= $(HOME)/.ssh/id_rsa.pub
SCP_REMOTEUSER_RECURSIVE_FLAG?= false
# SCP_REMOTEUSER_REMOTEDESTINATION_FILEPATH?=
SCP_REMOTEUSER_REMOTEFILE_DIRPATH?= ~/
# SCP_REMOTEUSER_REMOTEFILE_FILENAME?= script.sh
# SCP_REMOTEUSER_REMOTEFILE_FILEPATH?= /tmp/script.sh
# SCP_REMOTEUSER_REMOTESOURCE_FILEPATH?=
# SCP_REMOTEUSER_SHORTNAME?= ubuntu

# Derived parameters 
SCP_REMOTEUSER_CONFIG_DIRPATH?= $(SCP_CONFIG_DIRPATH)
SCP_REMOTEUSER_CONFIG_FILENAME?= $(SCP_CONFIG_FILENAME)
SCP_REMOTEUSER_CONFIG_FILEPATH?= $(SCP_REMOTEUSER_CONFIG_DIRPATH)$(SCP_REMOTEUSER_CONFIG_FILENAME)
SCP_REMOTEUSER_HOST_IP_OR_NAME?= $(if $(SCP_REMOTEUSER_HOST_IP),$(SCP_REMOTEUSER_HOST_IP),$(SCP_REMOTEUSER_HOST_NAME))
SCP_REMOTEUSER_HOST_PORT?= $(SCP_HOST_PORT)
SCP_REMOTEUSER_LOCALFILE_DIRPATH?= $(SCP_INPUTS_DIRPATH)
SCP_REMOTEUSER_LOCALFILE_FILEPATH?= $(SCP_REMOTEUSER_LOCALFILE_DIRPATH)$(SCP_REMOTEUSER_LOCALFILE_FILENAME)
SCP_REMOTEUSER_NAME?= $(if $(SCP_REMOTEUSER_SHORTNAME),$(SCP_REMOTEUSER_SHORTNAME)@$(SCP_REMOTEUSER_HOST_IP_OR_NAME))
SCP_REMOTEUSER_PRIVATEKEY_FILEPATH?= $(SCP_KEYPAIR_PRIVATEKEY_FILEPATH)
SCP_REMOTEUSER_PUBLICKEY_FILEPATH?= $(SCP_KEYPAIR_PUBLICKEY_FILEPATH)
SCP_REMOTEUSER_REMOTEDESTINATION_FILEPATH?= $(SCP_REMOTEUSER_REMOTEFILE_FILEPATH)
# SCP_REMOTEUSER_REMOTEFILE_DIRPATH?= $(SCP_REMOTEUSER_LOCALFILE_DIRPATH)
SCP_REMOTEUSER_REMOTEFILE_FILENAME?= $(SCP_REMOTEUSER_LOCALFILE_FILENAME)
SCP_REMOTEUSER_REMOTEFILE_FILEPATH?= $(SCP_REMOTEUSER_REMOTEFILE_DIRPATH)$(SCP_REMOTEUSER_REMOTEFILE_FILENAME)
SCP_REMOTEUSER_REMOTESOURCE_FILEPATH?= $(SCP_REMOTEUSER_REMOTEFILE_FILEPATH)
SCP_REMOTEUSER_SHORTNAME?= $(USER)

# Option parameters
__SCP_CONFIG__REMOTEUSER= $(if $(SCP_REMOTEUSER_CONFIG_FILEPATH),-F $(SCP_REMOTEUSER_CONFIG_FILEPATH))
__SCP_IDENTITY__REMOTEUSER= $(if $(SCP_REMOTEUSER_PRIVATEKEY_FILEPATH),-i $(SCP_REMOTEUSER_PRIVATEKEY_FILEPATH))
__SCP_PORT__REMOTEUSER= $(if $(SCP_REMOTEUSER_HOST_PORT),-P $(SCP_REMOTEUSER_HOST_PORT))
__SCP_PRESERVE= $(if $(filter true,$(SCP_REMOTEUSER_PRESERVE_FLAG)),-p)
__SCP_RECURSIVE= $(if $(filter true,$(SCP_REMOTEUSER_RECURSIVE_FLAG)),-r)

#--- Utilities

#--- Macros

#----------------------------------------------------------------------
# USAGE
#

_scp_view_framework_macros ::
	@#echo 'SCP::RemoteUser ($(_SCP_REMOTEUSER_MK_VERSION)) macros:'
	@#echo

_scp_view_framework_parameters ::
	@echo 'SCP::RemoteUser ($(_SCP_REMOTEUSER_MK_VERSION)) parameters:'
	@echo '    SCP_REMOTEUSER_CONFIG_DIRPATH=$(SCP_REMOTEUSER_CONFIG_DIRPATH)'
	@echo '    SCP_REMOTEUSER_CONFIG_FILENAME=$(SCP_REMOTEUSER_CONFIG_FILENAME)'
	@echo '    SCP_REMOTEUSER_CONFIG_FILEPATH=$(SCP_REMOTEUSER_CONFIG_FILEPATH)'
	@echo '    SCP_REMOTEUSER_HOST_IP=$(SCP_REMOTEUSER_HOST_IP)'
	@echo '    SCP_REMOTEUSER_HOST_IP_OR_NAME=$(SCP_REMOTEUSER_HOST_IP_OR_NAME)'
	@echo '    SCP_REMOTEUSER_HOST_PORT=$(SCP_REMOTEUSER_HOST_PORT)'
	@echo '    SCP_REMOTEUSER_HOST_NAME=$(SCP_REMOTEUSER_HOST_NAME)'
	@echo '    SCP_REMOTEUSER_LOCALFILE_DIRPATH=$(SCP_REMOTEUSER_LOCALFILE_DIRPATH)'
	@echo '    SCP_REMOTEUSER_LOCALFILE_FILENAME=$(SCP_REMOTEUSER_LOCALFILE_FILENAME)'
	@echo '    SCP_REMOTEUSER_LOCALFILE_FILEPATH=$(SCP_REMOTEUSER_LOCALFILE_FILEPATH)'
	@echo '    SCP_REMOTEUSER_NAME=$(SCP_REMOTEUSER_NAME)'
	@echo '    SCP_REMOTEUSER_PRESERVE_FLAG=$(SCP_REMOTEUSER_PRESERVE_FLAG)'
	@echo '    SCP_REMOTEUSER_PRIVATEKEY_FILEPATH=$(SCP_REMOTEUSER_PRIVATEKEY_FILEPATH)'
	@echo '    SCP_REMOTEUSER_PUBLICKEY_FILEPATH=$(SCP_REMOTEUSER_PUBLICKEY_FILEPATH)'
	@echo '    SCP_REMOTEUSER_RECURSIVE_FLAG=$(SCP_REMOTEUSER_RECURSIVE_FLAG)'
	@echo '    SCP_REMOTEUSER_REMOTEDESTINATION_FILEPATH=$(SCP_REMOTEUSER_REMOTEDESTINATION_FILEPATH)'
	@echo '    SCP_REMOTEUSER_REMOTEFILE_DIRPATH=$(SCP_REMOTEUSER_REMOTEFILE_DIRPATH)'
	@echo '    SCP_REMOTEUSER_REMOTEFILE_FILENAME=$(SCP_REMOTEUSER_REMOTEFILE_FILENAME)'
	@echo '    SCP_REMOTEUSER_REMOTEFILE_FILEPATH=$(SCP_REMOTEUSER_REMOTEFILE_FILEPATH)'
	@echo '    SCP_REMOTEUSER_REMOTESOURCE_FILEPATH=$(SCP_REMOTEUSER_REMOTESOURCE_FILEPATH)'
	@echo '    SCP_REMOTEUSER_SHORTNAME=$(SCP_REMOTEUSER_SHORTNAME)'
	@echo

_scp_view_framework_targets ::
	@echo 'SCP::RemoteUser ($(_SCP_REMOTEUSER_MK_VERSION)) targets:'
	@echo '    _scp_copyfrom_remoteuser            - Copy from a remote-user'
	@echo '    _scp_copyto_remoteuser              - Copy to a remote-user'
	@echo '    _scp_rcopy_remoteuser               - Copy remotely from and to a remote-user'
	@echo

#----------------------------------------------------------------------
# SCP KEY MANAGEMENT
#

_scp_copyfrom_remoteuser:
	@$(INFO) '$(SCP_UI_LABEL)Copying-from remote-user "$(SCP_REMOTEUSER_NAME)" ...'; $(NORMAL)
	@$(WARN) 'This operation fails if the local directory does NOT exist'; $(NORMAL)
	$(SCP) $(__SCP_CONFIG__REMOTEUSER) $(__SCP_IDENTITY__REMOTEUSER) $(__SCP_PORT__REMOTEUSER) $(__SCP_PRESERVE) $(__SCP_RECURSIVE) $(SCP_REMOTEUSER_NAME):$(SCP_REMOTEUSER_REMOTEFILE_FILEPATH) $(SCP_REMOTEUSER_LOCALFILE_FILEPATH)

_scp_copyto_remoteuser:
	@$(INFO) '$(SCP_UI_LABEL)Copying-to remote-user "$(SCP_REMOTEUSER_NAME)" ...'; $(NORMAL)
	@$(WARN) 'This operation fails if the remote directory does NOT exist'; $(NORMAL)
	$(SCP) $(__SCP_CONFIG__REMOTEUSER) $(__SCP_IDENTITY__REMOTEUSER) $(__SCP_PORT__REMOTEUSER) $(__SCP_PRESERVE) $(__SCP_RECURSIVE) $(SCP_REMOTEUSER_LOCALFILE_FILEPATH) $(SCP_REMOTEUSER_NAME):$(SCP_REMOTEUSER_REMOTEFILE_FILEPATH)

_scp_rcopy_remoteuser:
	@$(INFO) '$(SCP_UI_LABEL)Remote-copying as remote-user "$(SCP_REMOTEUSER_NAME)" ...'; $(NORMAL)
	$(SCP) $(__SCP_CONFIG__REMOTEUSER) $(__SCP_IDENTITY__REMOTEUSER) $(__SCP_PORT__REMOTEUSER) $(__SCP_PRESERVE) $(__SCP_RECURSIVE) $(SCP_REMOTEUSER_NAME):$(SCP_REMOTEUSER_REMOTESOURCE_FILEPATH) $(SCP_REMOTEUSER_NAME):$(SCP_REMOTEUSER_REMOTEDESTINATION_FILEPATH)
