_STERN_MK_VERSION= 0.99

# STN_CLUSTER_NAME?= my-cluster
# STN_CLUSTER_TAILCOLOR_MODE?= auto
# STN_CLUSTER_TAILCONTAINERS_STATE?= running
# STN_CLUSTER_TAILEXCLUDECONTAINERS_REGEX?= "istio-|fluentd-.*"
# STN_CLUSTER_TAILEXCLUDELOGLINES_REGEX?= "^POST|HealthChecker"
STN_CLUSTER_TAILHISTORY_COUNT?= 0# -1
STN_CLUSTER_TAILPODS_REGEX?= '.*'#
#
# STN_DEPLOYMENT_NAME?= my-deployment
# STN_DEPLOYMENT_NAMESPACE_NAME?= my-namespace
# STN_DEPLOYMENT_TAILCOLOR_MODE?= auto
# STN_DEPLOYMENT_TAILCONTAINERS_STATE?= running
# STN_DEPLOYMENT_TAILEXCLUDECONTAINERS_REGEX?= "istio-|fluentd-.*"
# STN_DEPLOYMENT_TAILEXCLUDELOGLINES_REGEX?= "^POST|HealthChecker"
# STN_DEPLOYMENT_TAILHISTORY_COUNT?= 0# -1
# STN_DEPLOYMENT_TAILPODS_REGEX?= '^my-deployment-*'#
#
# STN_NAMESPACE_NAME?= my-namespace
# STN_NAMESPACE_TAILCOLOR_MODE?= auto
# STN_NAMESPACE_TAILCONTAINERS_STATE?= running
# STN_NAMESPACE_TAILEXCLUDECONTAINERS_REGEX?= "istio-|fluentd-.*"
# STN_NAMESPACE_TAILEXCLUDELOGLINES_REGEX?= "^POST|HealthChecker"
STN_NAMESPACE_TAILHISTORY_COUNT?= 0# -1
STN_NAMESPACE_TAILPODS_REGEX?= '.*'#
#
# STN_POD_NAME?= my-deployment
# STN_POD_NAMESPACE_NAME?= my-namespace
# STN_POD_TAILCOLOR_MODE?= auto
# STN_POD_TAILCONTAINERS_STATE?= running
# STN_POD_TAILEXCLUDECONTAINERS_REGEX?= "istio-|fluentd-.*"
# STN_POD_TAILEXCLUDELOGLINES_REGEX?= "^POST|HealthChecker"
# STN_POD_TAILHISTORY_COUNT?= 0# -1
# STN_POD_TAILPODS_REGEX?= '^my-deployment-*'#
#
# STN_SERVICE_NAME?= my-service
# STN_SERVICE_NAMESPACE_NAME?= my-namespace
# STN_SERVICE_TAILCOLOR_MODE?= auto
# STN_SERVICE_TAILCONTAINERS_STATE?= running
# STN_SERVICE_TAILEXCLUDECONTAINERS_REGEX?= "istio-|fluentd-.*"
# STN_SERVICE_TAILEXCLUDELOGLINES_REGEX?= "^POST|HealthChecker"
# STN_SERVICE_TAILHISTORY_COUNT?= -1
# STN_SERVICE_TAILPODS_REGEX?= '.*'#

STN_TAILS_COLOR_MODE?= auto
STN_TAILS_CONTAINERS_STATE?= running
# STN_TAILS_EXCLUDECONTAINERS_REGEX?= "istio-|fluentd-.*"
# STN_TAILS_EXCLUDELOGLINES_REGEX?= "^POST|HealthChecker"
STN_TAILS_HISTORY_COUNT?= -1
STN_TAILS_OUTPUT_MODE?= default
# STN_TAILS_SINCE_DURATION?= 2m
STN_TAILS_TIMESTAMP_FLAG?= false


# Derived parameters
STN_CLUSTER_NAME?= $(KCL_CLUSTER_NAME)
STN_CLUSTER_TAILCOLOR_MODE?= $(STN_TAILS_COLOR_MODE)
STN_CLUSTER_TAILCONTAINERS_STATE?= $(STN_TAILS_CONTAINERS_STATE)
STN_CLUSTER_TAILEXCLUDECONTAINERS_REGEX?= $(STN_TAILS_EXCLUDECONTAINERS_REGEX)
STN_CLUSTER_TAILEXCLUDELOGLINES_REGEX?= $(STN_TAILS_EXCLUDELOGLINES_REGEX)
# STN_CLUSTER_TAILHISTORY_COUNT?= $(STN_TAILS_HISTORY_COUNT)

STN_DEPLOYMENT_NAME?= $(KCL_DEPLOYMENT_NAME)
STN_DEPLOYMENT_NAMESPACE_NAME?= $(KCL_DEPLOYMENT_NAMESPACE_NAME)
STN_DEPLOYMENT_TAILCOLOR_MODE?= $(STN_TAILS_COLOR_MODE)
STN_DEPLOYMENT_TAILCONTAINERS_STATE?= $(STN_TAILS_CONTAINERS_STATE)
STN_DEPLOYMENT_TAILEXCLUDECONTAINERS_REGEX?= $(STN_TAILS_EXCLUDECONTAINERS_REGEX)
STN_DEPLOYMENT_TAILEXCLUDELOGLINES_REGEX?= $(STN_TAILS_EXCLUDELOGLINES_REGEX)
STN_DEPLOYMENT_TAILHISTORY_COUNT?= $(STN_TAILS_HISTORY_COUNT)
STN_DEPLOYMENT_TAILPODS_REGEX?= '^$(STN_DEPLOYMENT_NAME)*'#

STN_NAMESPACE_NAME?= $(KCL_NAMESPACE_NAME)
STN_NAMESPACE_TAILCOLOR_MODE?= $(STN_TAILCOLOR_MODE)
STN_NAMESPACE_TAILCONTAINERS_STATE?= $(STN_TAILS_CONTAINERS_STATE)
STN_NAMESPACE_TAILEXCLUDECONTAINERS_REGEX?= $(STN_TAILS_EXCLUDECONTAINERS_REGEX)
STN_NAMESPACE_TAILEXCLUDELOGLINES_REGEX?= $(STN_TAILS_EXCLUDELOGLINES_REGEX)
# STN_NAMESPACE_TAILHISTORY_COUNT?= $(STN_TAILS_HISTORY_COUNT)

STN_POD_NAME?= $(KCL_POD_NAME)
STN_POD_NAMESPACE_NAME?= $(KCL_POD_NAMESPACE_NAME)
STN_POD_TAILCOLOR_MODE?= $(STN_TAILS_COLOR_MODE)
STN_POD_TAILCONTAINERS_STATE?= $(STN_TAILS_CONTAINERS_STATE)
STN_POD_TAILEXCLUDECONTAINERS_REGEX?= $(STN_TAILS_EXCLUDECONTAINERS_REGEX)
STN_POD_TAILEXCLUDELOGLINES_REGEX?= $(STN_TAILS_EXCLUDELOGLINES_REGEX)
STN_POD_TAILHISTORY_COUNT?= $(STN_TAILS_HISTORY_COUNT)

STN_SERVICE_NAME?= $(KCL_SERVICE_NAME)
STN_SERVICE_NAMESPACE_NAME?= $(KCL_SERVICE_NAMESPACE_NAME)
STN_SERVICE_TAILCOLOR_MODE?= $(STN_TAILS_COLOR_MODE)
STN_SERVICE_TAILCONTAINERS_STATE?= $(STN_TAILS_CONTAINERS_STATE)
STN_SERVICE_TAILEXCLUDECONTAINERS_REGEX?= $(STN_TAILS_EXCLUDECONTAINERS_REGEX)
STN_SERVICE_TAILEXCLUDELOGLINES_REGEX?= $(STN_TAILS_EXCLUDELOGLINES_REGEX)
STN_SERVICE_TAILHISTORY_COUNT?= $(STN_TAILS_HISTORY_COUNT)
STN_SERVICE_TAILPODS_REGEX?= '^$(STN_SERVICE_NAME)*'#

# Option parameters
__STN_OUTPUT= $(if $(STN_TAILS_OUTPUT_MODE),--output $(STN_TAILS_OUTPUT_MODE))
__STN_SINCE= $(if $(STN_TAILS_SINCE_DURATION),--since $(STN_TAILS_SINCE_DURATION))
__STN_TIMESTAMPS= $(if $(filter true, $(STN_TAILS_TIMESTAMP_FLAG)),--timestamps)

__STN_COLOR__CLUSTER= $(if $(STN_CLUSTER_TAILCOLOR_MODE),--color $(STN_CLUSTER_TAILCOLOR_MODE))
__STN_CONTAINER_STATE__CLUSTER= $(if $(STN_CLUSTER_TAILCONTAINERS_STATE),--container-state $(STN_CLUSTER_TAILCONTAINERS_STATE))
__STN_EXCLUDE__CLUSTER= $(if $(STN_CLUSTER_TAILEXCLUDELOGLINES_REGEX),--exclude $(STN_CLUSTER_TAILEXCLUDELOGLINES_REGEX))
__STN_EXCLUDE_CONTAINER__CLUSTER= $(if $(STN_CLUSTER_TAILEXCLUDECONTAINERS_REGEX),--exclude-container $(STN_CLUSTER_TAILEXCLUDECONTAINERS_REGEX))
__STN_TAIL__CLUSTER= $(if $(STN_CLUSTER_TAILHISTORY_COUNT),--tail $(STN_CLUSTER_TAILHISTORY_COUNT))

__STN_COLOR__DEPLOYMENT= $(if $(STN_DEPLOYMENT_TAILCOLOR_MODE),--color $(STN_DEPLOYMENT_TAILCOLOR_MODE))
__STN_CONTAINER_STATE__DEPLOYMENT= $(if $(STN_DEPLOYMENT_TAILCONTAINERS_STATE),--container-state $(STN_DEPLOYMENT_TAILCONTAINERS_STATE))
__STN_EXCLUDE__DEPLOYMENT= $(if $(STN_DEPLOYMENT_TAILEXCLUDELOGLINES_REGEX),--exclude $(STN_DEPLOYMENT_TAILEXCLUDELOGLINES_REGEX))
__STN_EXCLUDE_CONTAINER__DEPLOYMENT= $(if $(STN_DEPLOYMENT_TAILEXCLUDECONTAINERS_REGEX),--exclude-container $(STN_DEPLOYMENT_TAILEXCLUDECONTAINERS_REGEX))
__STN_NAMESPACE__DEPLOYMENT= $(if $(STN_DEPLOYMENT_NAMESPACE_NAME),--namespace $(STN_DEPLOYMENT_NAMESPACE_NAME))
__STN_TAIL__DEPLOYMENT= $(if $(STN_DEPLOYMENT_TAILHISTORY_COUNT),--tail $(STN_DEPLOYMENT_TAILHISTORY_COUNT))

__STN_COLOR__NAMESPACE= $(if $(STN_NAMESPACE_TAILCOLOR_MODE),--color $(STN_NAMESPACE_TAILCOLOR_MODE))
__STN_CONTAINER_STATE__NAMESPACE= $(if $(STN_NAMESPACE_TAILCONTAINERS_STATE),--container-state $(STN_NAMESPACE_TAILCONTAINERS_STATE))
__STN_EXCLUDE__NAMESPACE= $(if $(STN_NAMESPACE_TAILEXCLUDELOGLINES_REGEX),--exclude $(STN_NAMESPACE_TAILEXCLUDELOGLINES_REGEX))
__STN_EXCLUDE_CONTAINER__NAMESPACE= $(if $(STN_NAMESPACE_TAILEXCLUDECONTAINERS_REGEX),--exclude-container $(STN_NAMESPACE_TAILEXCLUDECONTAINERS_REGEX))
__STN_NAMESPACE__NAMESPACE= $(if $(STN_NAMESPACE_NAME),--namespace $(STN_NAMESPACE_NAME))
__STN_TAIL__NAMESPACE= $(if $(STN_NAMESPACE_TAILHISTORY_COUNT),--tail $(STN_NAMESPACE_TAILHISTORY_COUNT))

__STN_COLOR__POD= $(if $(STN_POD_TAILCOLOR_MODE),--color $(STN_POD_TAILCOLOR_MODE))
__STN_CONTAINER_STATE__POD= $(if $(STN_POD_TAILCONTAINERS_STATE),--container-state $(STN_POD_TAILCONTAINERS_STATE))
__STN_EXCLUDE__POD= $(if $(STN_POD_TAILEXCLUDELOGLINES_REGEX),--exclude $(STN_POD_TAILEXCLUDELOGLINES_REGEX))
__STN_EXCLUDE_CONTAINER__POD= $(if $(STN_POD_TAILEXCLUDECONTAINERS_REGEX),--exclude-container $(STN_POD_TAILEXCLUDECONTAINERS_REGEX))
__STN_NAMESPACE__POD= $(if $(STN_POD_NAMESPACE_NAME),--namespace $(STN_POD_NAMESPACE_NAME))
__STN_TAIL__POD= $(if $(STN_POD_TAILHISTORY_COUNT),--tail $(STN_POD_TAILHISTORY_COUNT))

__STN_COLOR__SERVICE= $(if $(STN_SERVICE_TAILCOLOR_MODE),--color $(STN_SERVICE_TAILCOLOR_MODE))
__STN_CONTAINER_STATE__SERVICE= $(if $(STN_SERVICE_TAILCONTAINERS_STATE),--container-state $(STN_SERVICE_TAILCONTAINERS_STATE))
__STN_EXCLUDE__SERVICE= $(if $(STN_SERVICE_TAILEXCLUDELOGLINES_REGEX),--exclude $(STN_SERVICE_TAILEXCLUDELOGLINES_REGEX))
__STN_EXCLUDE_CONTAINER__SERVICE= $(if $(STN_SERVICE_TAILEXCLUDECONTAINERS_REGEX),--exclude-container $(STN_SERVICE_TAILEXCLUDECONTAINERS_REGEX))
__STN_NAMESPACE__SERVICE= $(if $(STN_SERVICE_NAMESPACE_NAME),--namespace $(STN_SERVICE_NAMESPACE_NAME))
__STN_TAIL__SERVICE= $(if $(STN_SERVICE_TAILHISTORY_COUNT),--tail $(STN_SERVICE_TAILHISTORY_COUNT))

# UI parameters
STN_UI_LABEL?= [stern] #

# Pipe parameters
_STN_TAIL_CLUSTER_|?=
|_STN_TAIL_CLUSTER?= # | tee cluster.log
_STN_TAIL_DEPLOYMENT|?=
|_STN_TAIL_DEPLOYMENT?= # | tee deployment.log
_STN_TAIL_NAMESPACE|?=
|_STN_TAIL_NAMESPACE?= # | tee namespace.log
_STN_TAIL_POD|?=
|_STN_TAIL_PODS?= # | tee namespace.log
_STN_TAIL_SERVICE_|?=
|_STN_TAIL_SERVICE?= # | tee service.log

#--- MACROS
STERN_KUBECONFIG_FILEPATH?= $(KUBECTL_KUBECONFIG_FILEPATH)
__STERN_OPTIONS+= $(if $(STERN_KUBECONFIG_FILEPATH),--kubeconfig $(STERN_KUBECONFIG_FILEPATH))
STERN_BIN?= stern
STERN?= $(strip $(__STERN_ENVIRONMENT) $(STERN_ENVIRONMENT) $(STERN_BIN) $(__STERN_OPTIONS) $(STERN_OPTIONS))

#----------------------------------------------------------------------
# USAGE
#

_view_framework_macros :: _stn_view_framework_macros
_stn_view_framework_macros ::
	@echo 'STerN:: ($(_STERN_MK_VERSION)) macros:'
	@echo

_view_framework_parameters :: _stn_view_framework_parameters
_stn_view_framework_parameters ::
	@echo 'STerN:: ($(_STERN_MK_VERSION)) parameters:'
	@echo '    STERN=$(STERN)'
	@echo '    STN_CLUSTER_NAME=$(STN_CLUSTER_NAME)'
	@echo '    STN_CLUSTER_TAILCOLOR_MODE=$(STN_CLUSTER_TAILCOLOR_MODE)'
	@echo '    STN_CLUSTER_TAILCONTAINERS_STATE=$(STN_CLUSTER_TAILCONTAINERS_STATE)'
	@echo '    STN_CLUSTER_TAILHISTORY_COUNT=$(STN_CLUSTER_TAILHISTORY_COUNT)'
	@echo '    STN_CLUSTER_TAILEXCLUDECONTAINERS_REGEX=$(STN_CLUSTER_TAILEXCLUDECONTAINERS_REGEX)'
	@echo '    STN_CLUSTER_TAILEXCLUDELOGLINES_REGEX=$(STN_CLUSTER_TAILEXCLUDELOGLINES_REGEX)'
	@echo '    STN_CLUSTER_TAILPODS_REGEX=$(STN_CLUSTER_TAILPODS_REGEX)'
	@echo '    STN_DEPLOYMENT_NAME=$(STN_DEPLOYMENT_NAME)'
	@echo '    STN_DEPLOYMENT_NAMESPACE_NAME=$(STN_DEPLOYMENT_NAMESPACE_NAME)'
	@echo '    STN_DEPLOYMENT_TAILCOLOR_MODE=$(STN_DEPLOYMENT_TAILCOLOR_MODE)'
	@echo '    STN_DEPLOYMENT_TAILCONTAINERS_STATE=$(STN_DEPLOYMENT_TAILCONTAINERS_STATE)'
	@echo '    STN_DEPLOYMENT_TAILHISTORY_COUNT=$(STN_DEPLOYMENT_TAILHISTORY_COUNT)'
	@echo '    STN_DEPLOYMENT_TAILEXCLUDECONTAINERS_REGEX=$(STN_DEPLOYMENT_TAILEXCLUDECONTAINERS_REGEX)'
	@echo '    STN_DEPLOYMENT_TAILEXCLUDELOGLINES_REGEX=$(STN_DEPLOYMENT_TAILEXCLUDELOGLINES_REGEX)'
	@echo '    STN_DEPLOYMENT_TAILPODS_REGEX=$(STN_DEPLOYMENT_TAILPODS_REGEX)'
	@echo '    STN_NAMESPACE_NAME=$(STN_NAMESPACE_NAME)'
	@echo '    STN_NAMESPACE_TAILCOLOR_MODE=$(STN_NAMESPACE_TAILCOLOR_MODE)'
	@echo '    STN_NAMESPACE_TAILCONTAINERS_STATE=$(STN_NAMESPACE_TAILCONTAINERS_STATE)'
	@echo '    STN_NAMESPACE_TAILHISTORY_COUNT=$(STN_NAMESPACE_TAILHISTORY_COUNT)'
	@echo '    STN_NAMESPACE_TAILEXCLUDECONTAINERS_REGEX=$(STN_NAMESPACE_TAILEXCLUDECONTAINERS_REGEX)'
	@echo '    STN_NAMESPACE_TAILEXCLUDELOGLINES_REGEX=$(STN_NAMESPACE_TAILEXCLUDELOGLINES_REGEX)'
	@echo '    STN_NAMESPACE_TAILPODS_REGEX=$(STN_NAMESPACE_TAILPODS_REGEX)'
	@echo '    STN_POD_NAME=$(STN_POD_NAME)'
	@echo '    STN_POD_NAMESPACE_NAME=$(STN_POD_NAMESPACE_NAME)'
	@echo '    STN_POD_TAILCOLOR_MODE=$(STN_POD_TAILCOLOR_MODE)'
	@echo '    STN_POD_TAILCONTAINERS_STATE=$(STN_POD_TAILCONTAINERS_STATE)'
	@echo '    STN_POD_TAILHISTORY_COUNT=$(STN_POD_TAILHISTORY_COUNT)'
	@echo '    STN_POD_TAILEXCLUDECONTAINERS_REGEX=$(STN_POD_TAILEXCLUDECONTAINERS_REGEX)'
	@echo '    STN_POD_TAILEXCLUDELOGLINES_REGEX=$(STN_POD_TAILEXCLUDELOGLINES_REGEX)'
	@echo '    STN_SERVICE_NAME=$(STN_SERVICE_NAME)'
	@echo '    STN_SERVICE_NAMESPACE_NAME=$(STN_SERVICE_NAMESPACE_NAME)'
	@echo '    STN_SERVICE_TAILCOLOR_MODE=$(STN_SERVICE_TAILCOLOR_MODE)'
	@echo '    STN_SERVICE_TAILCONTAINERS_STATE=$(STN_SERVICE_TAILCONTAINERS_STATE)'
	@echo '    STN_SERVICE_TAILHISTORY_COUNT=$(STN_SERVICE_TAILHISTORY_COUNT)'
	@echo '    STN_SERVICE_TAILEXCLUDECONTAINERS_REGEX=$(STN_SERVICE_TAILEXCLUDECONTAINERS_REGEX)'
	@echo '    STN_SERVICE_TAILEXCLUDELOGLINES_REGEX=$(STN_SERVICE_TAILEXCLUDELOGLINES_REGEX)'
	@echo '    STN_SERVICE_TAILPODS_REGEX=$(STN_SERVICE_TAILPODS_REGEX)'
	@echo '    STN_TAILS_COLOR_MODE=$(STN_TAILS_COLOR_MODE)'
	@echo '    STN_TAILS_CONTAINERS_STATE=$(STN_TAILS_CONTAINERS_STATE)'
	@echo '    STN_TAILS_HISTORY_COUNT=$(STN_TAILS_HISTORY_COUNT)'
	@echo '    STN_TAILS_EXCLUDECONTAINERS_REGEX=$(STN_TAILS_EXCLUDECONTAINERS_REGEX)'
	@echo '    STN_TAILS_EXCLUDELOGLINES_REGEX=$(STN_TAILS_EXCLUDELOGLINES_REGEX)'
	@echo '    STN_TAILS_OUTPUT_MODE=$(STN_TAILS_OUTPUT_MODE)'
	@echo '    STN_TAILS_SINCE_DURATION=$(STN_TAILS_SINCE_DURATION)'
	@echo '    STN_TAILS_TIMESTAMP_FLAG=$(STN_TAILS_TIMESTAMP_FLAG)'
	@echo

_view_framework_targets :: _stn_view_framework_targets
_stn_view_framework_targets ::
	@echo 'STerN:: ($(_STERN_MK_VERSION)) targets:'
	@echo '    _stn_tail_cluster             - Tail all containers/pods in a cluster'
	@echo '    _stn_tail_deployment          - Tail all containers/pods in a deployment'
	@echo '    _stn_tail_namespace           - Tail all containers/pods in a namespace'
	@echo '    _stn_tail_pod                 - Tail all containers in a pod'
	@echo '    _stn_tail_service             - Tail all pods endpoints of a service'
	@echo

#----------------------------------------------------------------------
# PUBLIC TARGETS
#

_stn_tail_cluster:
	@$(INFO) '$(STN_UI_LABEL)Tailing ALL pods in cluster "$(STN_CLUSTER_NAME)" ...'; $(NORMAL)
	$(_STN_TAIL_CLUSTER_|)$(STERN) --all-namespaces $(__STN_COLOR__CLUSTER) $(__STN_CONTAINER_STATE__CLUSTER) $(__STN_EXCLUDE__CLUSTER) $(__STN_EXCLUDE_CONTAINER__CLUSTER) $(_X__STN_NAMESPACE__CLUSTER) $(__STN_OUTPUT) $(__STN_SINCE) $(__STN_TAIL__CLUSTER) $(__STN_TIMESTAMPS) $(STN_CLUSTER_TAILPODS_REGEX) $(|_STN_TAIL_CLUSTER)

_stn_tail_deployment:
	@$(INFO) '$(STN_UI_LABEL)Tailing pods in deployment "$(STN_DEPLOYMENT_NAME)" ...'; $(NORMAL)
	@$(WARN) 'This operation tails ALL the pods in the provided deployment'; $(NORMAL)
	$(_STN_TAIL_DEPLOYMENT_|)$(STERN) $(_X__STN_ALL_NAMESPACES) $(__STN_COLOR__DEPLOYMENT) $(__STN_CONTAINER_STATE__DEPLOYMENT) $(__STN_EXCLUDE__DEPLOYMENT) $(__STN_EXCLUDE_CONTAINER__DEPLOYMENT) $(__STN_NAMESPACE__DEPLOYMENT) $(__STN_OUTPUT) $(__STN_SINCE) $(__STN_TAIL__DEPLOYMENT) $(__STN_TIMESTAMPS) $(STN_DEPLOYMENT_TAILPODS_REGEX) $(|_STN_TAIL_DEPLOYMENT)

_stn_tail_namespace:
	@$(INFO) '$(STN_UI_LABEL)Tailing pods in namespace "$(STN_NAMESPACE_NAME)" ...'; $(NORMAL)
	@$(WARN) 'This operation tails ALL the pods in the provided namespace'; $(NORMAL)
	$(_STN_TAIL_NAMESPACE_|)$(STERN) $(_X__STN_ALL_NAMESPACES) $(__STN_COLOR__NAMESPACE) $(__STN_CONTAINER_STATE__NAMESPACE) $(__STN_EXCLUDE__NAMESPACE) $(__STN_EXCLUDE_CONTAINER__NAMESPACE) $(__STN_NAMESPACE__NAMESPACE) $(__STN_OUTPUT) $(__STN_SINCE) $(__STN_TAIL__NAMESPACE)i $(__STN_TIMESTAMPS)  $(STN_NAMESPACE_TAILPODS_REGEX) $(|_STN_TAIL_NAMESPACE)

_stn_tail_pod:
	@$(INFO) '$(STN_UI_LABEL)Tailing containers in pod "$(STN_POD_NAME)" ...'; $(NORMAL)
	@$(WARN) 'This operation tails ALL the containers in the designated pod'; $(NORMAL)
	$(_STN_TAIL_POD_|)$(STERN) $(_X__STN_ALL_NAMESPACES) $(__STN_COLOR__POD) $(__STN_CONTAINER_STATE__POD) $(__STN_EXCLUDE__POD) $(__STN_EXCLUDE_CONTAINER__POD) $(__STN_NAMESPACE__POD) $(__STN_OUTPUT) $(__STN_SINCE) $(__STN_TAIL__POD) $(__STN_TIMESTAMPS) $(STN_POD_NAME) $(|_STN_TAIL_POD)

_stn_tail_service:
	@$(INFO) '$(STN_UI_LABEL)Tailing pods behind service "$(STN_SERVICE_NAME)" ...'; $(NORMAL)
	@$(WARN) 'This operation tails ALL the pods for the provided deployment'; $(NORMAL)
	$(_STN_TAIL_SERVICE_|)$(STERN) $(_X__STN_ALL_NAMESPACE) $(__STN_COLOR__SERVICE) $(__STN_CONTAINER_STATE__SERVICE) $(__STN_EXCLUDE__SERVICE) $(__STN_EXCLUDE_CONTAINER__SERVICE) $(__STN_NAMESPACE__SERVICE) $(__STN_OUTPUT) $(__STN_SINCE) $(__STN_TAIL__SERVICE) $(__STN_TIMESTAMPS) $(STN_SERVICE_TAILPODS_REGEX) $(|_STN_TAIL_SERVICE)
